/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.13
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.vpndetection.model.AccountApikey;
import io.vpndetection.model.AccountPlan;
import io.vpndetection.model.AccountUsage;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * AccountMe
 */
@JsonPropertyOrder({
  AccountMe.JSON_PROPERTY_ORG_ID,
  AccountMe.JSON_PROPERTY_APIKEY,
  AccountMe.JSON_PROPERTY_PLAN,
  AccountMe.JSON_PROPERTY_USAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AccountMe {
  public static final String JSON_PROPERTY_ORG_ID = "org_id";
  @javax.annotation.Nonnull
  private UUID orgId;

  public static final String JSON_PROPERTY_APIKEY = "apikey";
  @javax.annotation.Nonnull
  private AccountApikey apikey;

  public static final String JSON_PROPERTY_PLAN = "plan";
  @javax.annotation.Nonnull
  private AccountPlan plan;

  public static final String JSON_PROPERTY_USAGE = "usage";
  @javax.annotation.Nonnull
  private AccountUsage usage;

  public AccountMe() { 
  }

  public AccountMe orgId(@javax.annotation.Nonnull UUID orgId) {
    this.orgId = orgId;
    return this;
  }

  /**
   * The organization the key belongs to.
   * @return orgId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ORG_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getOrgId() {
    return orgId;
  }


  @JsonProperty(value = JSON_PROPERTY_ORG_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrgId(@javax.annotation.Nonnull UUID orgId) {
    this.orgId = orgId;
  }


  public AccountMe apikey(@javax.annotation.Nonnull AccountApikey apikey) {
    this.apikey = apikey;
    return this;
  }

  /**
   * Get apikey
   * @return apikey
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_APIKEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AccountApikey getApikey() {
    return apikey;
  }


  @JsonProperty(value = JSON_PROPERTY_APIKEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApikey(@javax.annotation.Nonnull AccountApikey apikey) {
    this.apikey = apikey;
  }


  public AccountMe plan(@javax.annotation.Nonnull AccountPlan plan) {
    this.plan = plan;
    return this;
  }

  /**
   * Get plan
   * @return plan
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PLAN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AccountPlan getPlan() {
    return plan;
  }


  @JsonProperty(value = JSON_PROPERTY_PLAN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlan(@javax.annotation.Nonnull AccountPlan plan) {
    this.plan = plan;
  }


  public AccountMe usage(@javax.annotation.Nonnull AccountUsage usage) {
    this.usage = usage;
    return this;
  }

  /**
   * Get usage
   * @return usage
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AccountUsage getUsage() {
    return usage;
  }


  @JsonProperty(value = JSON_PROPERTY_USAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsage(@javax.annotation.Nonnull AccountUsage usage) {
    this.usage = usage;
  }


  /**
   * Return true if this AccountMe object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountMe accountMe = (AccountMe) o;
    return Objects.equals(this.orgId, accountMe.orgId) &&
        Objects.equals(this.apikey, accountMe.apikey) &&
        Objects.equals(this.plan, accountMe.plan) &&
        Objects.equals(this.usage, accountMe.usage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orgId, apikey, plan, usage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountMe {\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    apikey: ").append(toIndentedString(apikey)).append("\n");
    sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `org_id` to the URL query string
    if (getOrgId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sorg_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrgId()))));
    }

    // add `apikey` to the URL query string
    if (getApikey() != null) {
      joiner.add(getApikey().toUrlQueryString(prefix + "apikey" + suffix));
    }

    // add `plan` to the URL query string
    if (getPlan() != null) {
      joiner.add(getPlan().toUrlQueryString(prefix + "plan" + suffix));
    }

    // add `usage` to the URL query string
    if (getUsage() != null) {
      joiner.add(getUsage().toUrlQueryString(prefix + "usage" + suffix));
    }

    return joiner.toString();
  }
}

