/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.16
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * AccountCreatedApikey
 */
@JsonPropertyOrder({
  AccountCreatedApikey.JSON_PROPERTY_RC,
  AccountCreatedApikey.JSON_PROPERTY_ID,
  AccountCreatedApikey.JSON_PROPERTY_NAME,
  AccountCreatedApikey.JSON_PROPERTY_KEY,
  AccountCreatedApikey.JSON_PROPERTY_KEY_PREFIX,
  AccountCreatedApikey.JSON_PROPERTY_ALLOWED_CIDRS,
  AccountCreatedApikey.JSON_PROPERTY_ALLOWED_SCOPES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AccountCreatedApikey {
  public static final String JSON_PROPERTY_RC = "rc";
  @javax.annotation.Nonnull
  private String rc;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_KEY = "key";
  @javax.annotation.Nonnull
  private String key;

  public static final String JSON_PROPERTY_KEY_PREFIX = "key_prefix";
  @javax.annotation.Nullable
  private String keyPrefix;

  public static final String JSON_PROPERTY_ALLOWED_CIDRS = "allowed_cidrs";
  @javax.annotation.Nullable
  private List<String> allowedCidrs = new ArrayList<>();

  public static final String JSON_PROPERTY_ALLOWED_SCOPES = "allowed_scopes";
  @javax.annotation.Nullable
  private List<String> allowedScopes = new ArrayList<>();

  public AccountCreatedApikey() { 
  }

  public AccountCreatedApikey rc(@javax.annotation.Nonnull String rc) {
    this.rc = rc;
    return this;
  }

  /**
   * Get rc
   * @return rc
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRc() {
    return rc;
  }


  @JsonProperty(value = JSON_PROPERTY_RC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRc(@javax.annotation.Nonnull String rc) {
    this.rc = rc;
  }


  public AccountCreatedApikey id(@javax.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public AccountCreatedApikey name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public AccountCreatedApikey key(@javax.annotation.Nonnull String key) {
    this.key = key;
    return this;
  }

  /**
   * The secret. Returned once, here, and never again.
   * @return key
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(@javax.annotation.Nonnull String key) {
    this.key = key;
  }


  public AccountCreatedApikey keyPrefix(@javax.annotation.Nullable String keyPrefix) {
    this.keyPrefix = keyPrefix;
    return this;
  }

  /**
   * Get keyPrefix
   * @return keyPrefix
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KEY_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getKeyPrefix() {
    return keyPrefix;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeyPrefix(@javax.annotation.Nullable String keyPrefix) {
    this.keyPrefix = keyPrefix;
  }


  public AccountCreatedApikey allowedCidrs(@javax.annotation.Nullable List<String> allowedCidrs) {
    this.allowedCidrs = allowedCidrs;
    return this;
  }

  public AccountCreatedApikey addAllowedCidrsItem(String allowedCidrsItem) {
    if (this.allowedCidrs == null) {
      this.allowedCidrs = new ArrayList<>();
    }
    this.allowedCidrs.add(allowedCidrsItem);
    return this;
  }

  /**
   * Get allowedCidrs
   * @return allowedCidrs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALLOWED_CIDRS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getAllowedCidrs() {
    return allowedCidrs;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOWED_CIDRS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowedCidrs(@javax.annotation.Nullable List<String> allowedCidrs) {
    this.allowedCidrs = allowedCidrs;
  }


  public AccountCreatedApikey allowedScopes(@javax.annotation.Nullable List<String> allowedScopes) {
    this.allowedScopes = allowedScopes;
    return this;
  }

  public AccountCreatedApikey addAllowedScopesItem(String allowedScopesItem) {
    if (this.allowedScopes == null) {
      this.allowedScopes = new ArrayList<>();
    }
    this.allowedScopes.add(allowedScopesItem);
    return this;
  }

  /**
   * Get allowedScopes
   * @return allowedScopes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALLOWED_SCOPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getAllowedScopes() {
    return allowedScopes;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOWED_SCOPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowedScopes(@javax.annotation.Nullable List<String> allowedScopes) {
    this.allowedScopes = allowedScopes;
  }


  /**
   * Return true if this AccountCreatedApikey object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountCreatedApikey accountCreatedApikey = (AccountCreatedApikey) o;
    return Objects.equals(this.rc, accountCreatedApikey.rc) &&
        Objects.equals(this.id, accountCreatedApikey.id) &&
        Objects.equals(this.name, accountCreatedApikey.name) &&
        Objects.equals(this.key, accountCreatedApikey.key) &&
        Objects.equals(this.keyPrefix, accountCreatedApikey.keyPrefix) &&
        Objects.equals(this.allowedCidrs, accountCreatedApikey.allowedCidrs) &&
        Objects.equals(this.allowedScopes, accountCreatedApikey.allowedScopes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rc, id, name, key, keyPrefix, allowedCidrs, allowedScopes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountCreatedApikey {\n");
    sb.append("    rc: ").append(toIndentedString(rc)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    keyPrefix: ").append(toIndentedString(keyPrefix)).append("\n");
    sb.append("    allowedCidrs: ").append(toIndentedString(allowedCidrs)).append("\n");
    sb.append("    allowedScopes: ").append(toIndentedString(allowedScopes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `rc` to the URL query string
    if (getRc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%src%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRc()))));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `key` to the URL query string
    if (getKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKey()))));
    }

    // add `key_prefix` to the URL query string
    if (getKeyPrefix() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skey_prefix%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKeyPrefix()))));
    }

    // add `allowed_cidrs` to the URL query string
    if (getAllowedCidrs() != null) {
      for (int i = 0; i < getAllowedCidrs().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sallowed_cidrs%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAllowedCidrs().get(i)))));
      }
    }

    // add `allowed_scopes` to the URL query string
    if (getAllowedScopes() != null) {
      for (int i = 0; i < getAllowedScopes().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sallowed_scopes%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAllowedScopes().get(i)))));
      }
    }

    return joiner.toString();
  }
}

