/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.16
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * AccountCreateApikeyRequest
 */
@JsonPropertyOrder({
  AccountCreateApikeyRequest.JSON_PROPERTY_NAME,
  AccountCreateApikeyRequest.JSON_PROPERTY_ALLOWED_SCOPES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AccountCreateApikeyRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_ALLOWED_SCOPES = "allowed_scopes";
  @javax.annotation.Nullable
  private List<String> allowedScopes = new ArrayList<>();

  public AccountCreateApikeyRequest() { 
  }

  public AccountCreateApikeyRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * A label you will recognise later. Shown wherever the key is listed.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public AccountCreateApikeyRequest allowedScopes(@javax.annotation.Nullable List<String> allowedScopes) {
    this.allowedScopes = allowedScopes;
    return this;
  }

  public AccountCreateApikeyRequest addAllowedScopesItem(String allowedScopesItem) {
    if (this.allowedScopes == null) {
      this.allowedScopes = new ArrayList<>();
    }
    this.allowedScopes.add(allowedScopesItem);
    return this;
  }

  /**
   * What the new key may do. Omit for a key that carries no named scope, which is the safe default.
   * @return allowedScopes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALLOWED_SCOPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getAllowedScopes() {
    return allowedScopes;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOWED_SCOPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowedScopes(@javax.annotation.Nullable List<String> allowedScopes) {
    this.allowedScopes = allowedScopes;
  }


  /**
   * Return true if this AccountCreateApikeyRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountCreateApikeyRequest accountCreateApikeyRequest = (AccountCreateApikeyRequest) o;
    return Objects.equals(this.name, accountCreateApikeyRequest.name) &&
        Objects.equals(this.allowedScopes, accountCreateApikeyRequest.allowedScopes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, allowedScopes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountCreateApikeyRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    allowedScopes: ").append(toIndentedString(allowedScopes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `allowed_scopes` to the URL query string
    if (getAllowedScopes() != null) {
      for (int i = 0; i < getAllowedScopes().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sallowed_scopes%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAllowedScopes().get(i)))));
      }
    }

    return joiner.toString();
  }
}

