/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.16
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.vpndetection.model.ApikeyDetail;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * ApikeyList
 */
@JsonPropertyOrder({
  ApikeyList.JSON_PROPERTY_RC,
  ApikeyList.JSON_PROPERTY_KEYS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ApikeyList {
  public static final String JSON_PROPERTY_RC = "rc";
  @javax.annotation.Nonnull
  private String rc;

  public static final String JSON_PROPERTY_KEYS = "keys";
  @javax.annotation.Nonnull
  private List<ApikeyDetail> keys = new ArrayList<>();

  public ApikeyList() { 
  }

  public ApikeyList rc(@javax.annotation.Nonnull String rc) {
    this.rc = rc;
    return this;
  }

  /**
   * Get rc
   * @return rc
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRc() {
    return rc;
  }


  @JsonProperty(value = JSON_PROPERTY_RC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRc(@javax.annotation.Nonnull String rc) {
    this.rc = rc;
  }


  public ApikeyList keys(@javax.annotation.Nonnull List<ApikeyDetail> keys) {
    this.keys = keys;
    return this;
  }

  public ApikeyList addKeysItem(ApikeyDetail keysItem) {
    if (this.keys == null) {
      this.keys = new ArrayList<>();
    }
    this.keys.add(keysItem);
    return this;
  }

  /**
   * Get keys
   * @return keys
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ApikeyDetail> getKeys() {
    return keys;
  }


  @JsonProperty(value = JSON_PROPERTY_KEYS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeys(@javax.annotation.Nonnull List<ApikeyDetail> keys) {
    this.keys = keys;
  }


  /**
   * Return true if this ApikeyList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApikeyList apikeyList = (ApikeyList) o;
    return Objects.equals(this.rc, apikeyList.rc) &&
        Objects.equals(this.keys, apikeyList.keys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rc, keys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApikeyList {\n");
    sb.append("    rc: ").append(toIndentedString(rc)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `rc` to the URL query string
    if (getRc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%src%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRc()))));
    }

    // add `keys` to the URL query string
    if (getKeys() != null) {
      for (int i = 0; i < getKeys().size(); i++) {
        if (getKeys().get(i) != null) {
          joiner.add(getKeys().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%skeys%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

