/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.15
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.vpndetection.model.BatchLookupError;
import io.vpndetection.model.LookupResponse;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * BatchLookupResponse
 */
@JsonPropertyOrder({
  BatchLookupResponse.JSON_PROPERTY_RESULTS,
  BatchLookupResponse.JSON_PROPERTY_ERRORS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class BatchLookupResponse {
  public static final String JSON_PROPERTY_RESULTS = "results";
  @javax.annotation.Nonnull
  private Map<String, LookupResponse> results = new HashMap<>();

  public static final String JSON_PROPERTY_ERRORS = "errors";
  @javax.annotation.Nonnull
  private Map<String, BatchLookupError> errors = new HashMap<>();

  public BatchLookupResponse() { 
  }

  public BatchLookupResponse results(@javax.annotation.Nonnull Map<String, LookupResponse> results) {
    this.results = results;
    return this;
  }

  public BatchLookupResponse putResultsItem(String key, LookupResponse resultsItem) {
    if (this.results == null) {
      this.results = new HashMap<>();
    }
    this.results.put(key, resultsItem);
    return this;
  }

  /**
   * One answer per input string that was classified, keyed by the string as you sent it; the &#x60;ip&#x60; inside is the normalized form. Each value is exactly what &#x60;GET /{ip}&#x60; answers for your plan. 
   * @return results
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, LookupResponse> getResults() {
    return results;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResults(@javax.annotation.Nonnull Map<String, LookupResponse> results) {
    this.results = results;
  }


  public BatchLookupResponse errors(@javax.annotation.Nonnull Map<String, BatchLookupError> errors) {
    this.errors = errors;
    return this;
  }

  public BatchLookupResponse putErrorsItem(String key, BatchLookupError errorsItem) {
    if (this.errors == null) {
      this.errors = new HashMap<>();
    }
    this.errors.put(key, errorsItem);
    return this;
  }

  /**
   * One entry per input string that could not be classified, keyed the same way. Empty when every entry was answered. 
   * @return errors
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, BatchLookupError> getErrors() {
    return errors;
  }


  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setErrors(@javax.annotation.Nonnull Map<String, BatchLookupError> errors) {
    this.errors = errors;
  }


  /**
   * Return true if this BatchLookupResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchLookupResponse batchLookupResponse = (BatchLookupResponse) o;
    return Objects.equals(this.results, batchLookupResponse.results) &&
        Objects.equals(this.errors, batchLookupResponse.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(results, errors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchLookupResponse {\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `results` to the URL query string
    if (getResults() != null) {
      for (String _key : getResults().keySet()) {
        if (getResults().get(_key) != null) {
          joiner.add(getResults().get(_key).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sresults%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    // add `errors` to the URL query string
    if (getErrors() != null) {
      for (String _key : getErrors().keySet()) {
        if (getErrors().get(_key) != null) {
          joiner.add(getErrors().get(_key).toUrlQueryString(String.format(java.util.Locale.ROOT, "%serrors%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

