/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.18
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.vpndetection.model.Database;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * DatabaseList
 */
@JsonPropertyOrder({
  DatabaseList.JSON_PROPERTY_DATABASES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DatabaseList {
  public static final String JSON_PROPERTY_DATABASES = "databases";
  @javax.annotation.Nonnull
  private List<Database> databases = new ArrayList<>();

  public DatabaseList() { 
  }

  public DatabaseList databases(@javax.annotation.Nonnull List<Database> databases) {
    this.databases = databases;
    return this;
  }

  public DatabaseList addDatabasesItem(Database databasesItem) {
    if (this.databases == null) {
      this.databases = new ArrayList<>();
    }
    this.databases.add(databasesItem);
    return this;
  }

  /**
   * Get databases
   * @return databases
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATABASES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Database> getDatabases() {
    return databases;
  }


  @JsonProperty(value = JSON_PROPERTY_DATABASES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDatabases(@javax.annotation.Nonnull List<Database> databases) {
    this.databases = databases;
  }


  /**
   * Return true if this DatabaseList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatabaseList databaseList = (DatabaseList) o;
    return Objects.equals(this.databases, databaseList.databases);
  }

  @Override
  public int hashCode() {
    return Objects.hash(databases);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatabaseList {\n");
    sb.append("    databases: ").append(toIndentedString(databases)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `databases` to the URL query string
    if (getDatabases() != null) {
      for (int i = 0; i < getDatabases().size(); i++) {
        if (getDatabases().get(i) != null) {
          joiner.add(getDatabases().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdatabases%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

