/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.16
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.vpndetection.model.DatabaseVersion;
import io.vpndetection.model.Standing;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * One database FAMILY your organization is licensed for. A license covers the family, while a download names a specific version, so the ids you pass to the download and checksum endpoints come from &#x60;versions&#x60;. 
 */
@JsonPropertyOrder({
  Database.JSON_PROPERTY_BASE,
  Database.JSON_PROPERTY_NAME,
  Database.JSON_PROPERTY_SUMMARY,
  Database.JSON_PROPERTY_LICENSE_TYPE,
  Database.JSON_PROPERTY_STARTS,
  Database.JSON_PROPERTY_EXPIRES,
  Database.JSON_PROPERTY_RENEWS_AT,
  Database.JSON_PROPERTY_NOTICE_DUE_AT,
  Database.JSON_PROPERTY_IN_TERM,
  Database.JSON_PROPERTY_STANDING,
  Database.JSON_PROPERTY_VERSIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class Database {
  public static final String JSON_PROPERTY_BASE = "base";
  @javax.annotation.Nonnull
  private String base;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @javax.annotation.Nonnull
  private String summary;

  /**
   * What a license permits you to do with the data. Null for a family you hold no license for, which is every one with standing &#x60;unlicensed&#x60;. 
   */
  public enum LicenseTypeEnum {
    EVALUATION(String.valueOf("evaluation")),
    
    STANDARD(String.valueOf("standard")),
    
    REDISTRIBUTE(String.valueOf("redistribute"));

    private String value;

    LicenseTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LicenseTypeEnum fromValue(String value) {
      for (LicenseTypeEnum b : LicenseTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_LICENSE_TYPE = "license_type";
  @javax.annotation.Nullable
  private LicenseTypeEnum licenseType;

  public static final String JSON_PROPERTY_STARTS = "starts";
  @javax.annotation.Nullable
  private OffsetDateTime starts;

  public static final String JSON_PROPERTY_EXPIRES = "expires";
  @javax.annotation.Nullable
  private OffsetDateTime expires;

  public static final String JSON_PROPERTY_RENEWS_AT = "renews_at";
  @javax.annotation.Nullable
  private OffsetDateTime renewsAt;

  public static final String JSON_PROPERTY_NOTICE_DUE_AT = "notice_due_at";
  @javax.annotation.Nullable
  private OffsetDateTime noticeDueAt;

  public static final String JSON_PROPERTY_IN_TERM = "in_term";
  @javax.annotation.Nonnull
  private Boolean inTerm;

  public static final String JSON_PROPERTY_STANDING = "standing";
  @javax.annotation.Nonnull
  private Standing standing;

  public static final String JSON_PROPERTY_VERSIONS = "versions";
  @javax.annotation.Nonnull
  private List<DatabaseVersion> versions = new ArrayList<>();

  public Database() { 
  }

  public Database base(@javax.annotation.Nonnull String base) {
    this.base = base;
    return this;
  }

  /**
   * The database family, e.g. &#x60;vpn_ip&#x60;. What the license is held against.
   * @return base
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BASE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBase() {
    return base;
  }


  @JsonProperty(value = JSON_PROPERTY_BASE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBase(@javax.annotation.Nonnull String base) {
    this.base = base;
  }


  public Database name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public Database summary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSummary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
  }


  public Database licenseType(@javax.annotation.Nullable LicenseTypeEnum licenseType) {
    this.licenseType = licenseType;
    return this;
  }

  /**
   * What a license permits you to do with the data. Null for a family you hold no license for, which is every one with standing &#x60;unlicensed&#x60;. 
   * @return licenseType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LICENSE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public LicenseTypeEnum getLicenseType() {
    return licenseType;
  }


  @JsonProperty(value = JSON_PROPERTY_LICENSE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLicenseType(@javax.annotation.Nullable LicenseTypeEnum licenseType) {
    this.licenseType = licenseType;
  }


  public Database starts(@javax.annotation.Nullable OffsetDateTime starts) {
    this.starts = starts;
    return this;
  }

  /**
   * Get starts
   * @return starts
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STARTS, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getStarts() {
    return starts;
  }


  @JsonProperty(value = JSON_PROPERTY_STARTS, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStarts(@javax.annotation.Nullable OffsetDateTime starts) {
    this.starts = starts;
  }


  public Database expires(@javax.annotation.Nullable OffsetDateTime expires) {
    this.expires = expires;
    return this;
  }

  /**
   * A hard stop. Null when the license has no end date, which is the normal case for a rolling agreement, and when there is no license. A rolling license reports its turnover date in renews_at instead.
   * @return expires
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRES, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getExpires() {
    return expires;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpires(@javax.annotation.Nullable OffsetDateTime expires) {
    this.expires = expires;
  }


  public Database renewsAt(@javax.annotation.Nullable OffsetDateTime renewsAt) {
    this.renewsAt = renewsAt;
    return this;
  }

  /**
   * When a rolling license next renews. Null when the license has no defined term, when expires sets a hard stop instead, and when there is no license.
   * @return renewsAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RENEWS_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getRenewsAt() {
    return renewsAt;
  }


  @JsonProperty(value = JSON_PROPERTY_RENEWS_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRenewsAt(@javax.annotation.Nullable OffsetDateTime renewsAt) {
    this.renewsAt = renewsAt;
  }


  public Database noticeDueAt(@javax.annotation.Nullable OffsetDateTime noticeDueAt) {
    this.noticeDueAt = noticeDueAt;
    return this;
  }

  /**
   * The last day notice of non-renewal can be given for the term ending at renews_at. Null whenever renews_at is, and when the agreement records no notice period.
   * @return noticeDueAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NOTICE_DUE_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getNoticeDueAt() {
    return noticeDueAt;
  }


  @JsonProperty(value = JSON_PROPERTY_NOTICE_DUE_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNoticeDueAt(@javax.annotation.Nullable OffsetDateTime noticeDueAt) {
    this.noticeDueAt = noticeDueAt;
  }


  public Database inTerm(@javax.annotation.Nonnull Boolean inTerm) {
    this.inTerm = inTerm;
    return this;
  }

  /**
   * False when the license has lapsed; downloads are refused.
   * @return inTerm
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IN_TERM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getInTerm() {
    return inTerm;
  }


  @JsonProperty(value = JSON_PROPERTY_IN_TERM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInTerm(@javax.annotation.Nonnull Boolean inTerm) {
    this.inTerm = inTerm;
  }


  public Database standing(@javax.annotation.Nonnull Standing standing) {
    this.standing = standing;
    return this;
  }

  /**
   * Get standing
   * @return standing
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STANDING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Standing getStanding() {
    return standing;
  }


  @JsonProperty(value = JSON_PROPERTY_STANDING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStanding(@javax.annotation.Nonnull Standing standing) {
    this.standing = standing;
  }


  public Database versions(@javax.annotation.Nonnull List<DatabaseVersion> versions) {
    this.versions = versions;
    return this;
  }

  public Database addVersionsItem(DatabaseVersion versionsItem) {
    if (this.versions == null) {
      this.versions = new ArrayList<>();
    }
    this.versions.add(versionsItem);
    return this;
  }

  /**
   * Every published version of this family. The &#x60;id&#x60; here is what the download and checksum endpoints take. 
   * @return versions
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<DatabaseVersion> getVersions() {
    return versions;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersions(@javax.annotation.Nonnull List<DatabaseVersion> versions) {
    this.versions = versions;
  }


  /**
   * Return true if this Database object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Database database = (Database) o;
    return Objects.equals(this.base, database.base) &&
        Objects.equals(this.name, database.name) &&
        Objects.equals(this.summary, database.summary) &&
        Objects.equals(this.licenseType, database.licenseType) &&
        Objects.equals(this.starts, database.starts) &&
        Objects.equals(this.expires, database.expires) &&
        Objects.equals(this.renewsAt, database.renewsAt) &&
        Objects.equals(this.noticeDueAt, database.noticeDueAt) &&
        Objects.equals(this.inTerm, database.inTerm) &&
        Objects.equals(this.standing, database.standing) &&
        Objects.equals(this.versions, database.versions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(base, name, summary, licenseType, starts, expires, renewsAt, noticeDueAt, inTerm, standing, versions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Database {\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    licenseType: ").append(toIndentedString(licenseType)).append("\n");
    sb.append("    starts: ").append(toIndentedString(starts)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    renewsAt: ").append(toIndentedString(renewsAt)).append("\n");
    sb.append("    noticeDueAt: ").append(toIndentedString(noticeDueAt)).append("\n");
    sb.append("    inTerm: ").append(toIndentedString(inTerm)).append("\n");
    sb.append("    standing: ").append(toIndentedString(standing)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `base` to the URL query string
    if (getBase() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbase%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBase()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `summary` to the URL query string
    if (getSummary() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssummary%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSummary()))));
    }

    // add `license_type` to the URL query string
    if (getLicenseType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slicense_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLicenseType()))));
    }

    // add `starts` to the URL query string
    if (getStarts() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstarts%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStarts()))));
    }

    // add `expires` to the URL query string
    if (getExpires() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpires%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpires()))));
    }

    // add `renews_at` to the URL query string
    if (getRenewsAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srenews_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRenewsAt()))));
    }

    // add `notice_due_at` to the URL query string
    if (getNoticeDueAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snotice_due_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNoticeDueAt()))));
    }

    // add `in_term` to the URL query string
    if (getInTerm() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sin_term%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInTerm()))));
    }

    // add `standing` to the URL query string
    if (getStanding() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstanding%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStanding()))));
    }

    // add `versions` to the URL query string
    if (getVersions() != null) {
      for (int i = 0; i < getVersions().size(); i++) {
        if (getVersions().get(i) != null) {
          joiner.add(getVersions().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sversions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

