/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.09
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * DatasetFormatSize
 */
@JsonPropertyOrder({
  DatasetFormatSize.JSON_PROPERTY_FORMAT,
  DatasetFormatSize.JSON_PROPERTY_BYTES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DatasetFormatSize {
  /**
   * Gets or Sets format
   */
  public enum FormatEnum {
    CSVGZ(String.valueOf("csvgz")),
    
    MMDB(String.valueOf("mmdb"));

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FormatEnum fromValue(String value) {
      for (FormatEnum b : FormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FORMAT = "format";
  @javax.annotation.Nonnull
  private FormatEnum format;

  public static final String JSON_PROPERTY_BYTES = "bytes";
  @javax.annotation.Nullable
  private Integer bytes;

  public DatasetFormatSize() { 
  }

  public DatasetFormatSize format(@javax.annotation.Nonnull FormatEnum format) {
    this.format = format;
    return this;
  }

  /**
   * Get format
   * @return format
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public FormatEnum getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFormat(@javax.annotation.Nonnull FormatEnum format) {
    this.format = format;
  }


  public DatasetFormatSize bytes(@javax.annotation.Nullable Integer bytes) {
    this.bytes = bytes;
    return this;
  }

  /**
   * Size of the published file, or null when it has not been published yet
   * @return bytes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BYTES, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getBytes() {
    return bytes;
  }


  @JsonProperty(value = JSON_PROPERTY_BYTES, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBytes(@javax.annotation.Nullable Integer bytes) {
    this.bytes = bytes;
  }


  /**
   * Return true if this DatasetFormatSize object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetFormatSize datasetFormatSize = (DatasetFormatSize) o;
    return Objects.equals(this.format, datasetFormatSize.format) &&
        Objects.equals(this.bytes, datasetFormatSize.bytes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(format, bytes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetFormatSize {\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    bytes: ").append(toIndentedString(bytes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `format` to the URL query string
    if (getFormat() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sformat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFormat()))));
    }

    // add `bytes` to the URL query string
    if (getBytes() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbytes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBytes()))));
    }

    return joiner.toString();
  }
}

