/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.05
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.vpndetection.model.LicensedDataset;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * DatasetList
 */
@JsonPropertyOrder({
  DatasetList.JSON_PROPERTY_DATASETS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DatasetList {
  public static final String JSON_PROPERTY_DATASETS = "datasets";
  @javax.annotation.Nonnull
  private List<LicensedDataset> datasets = new ArrayList<>();

  public DatasetList() { 
  }

  public DatasetList datasets(@javax.annotation.Nonnull List<LicensedDataset> datasets) {
    this.datasets = datasets;
    return this;
  }

  public DatasetList addDatasetsItem(LicensedDataset datasetsItem) {
    if (this.datasets == null) {
      this.datasets = new ArrayList<>();
    }
    this.datasets.add(datasetsItem);
    return this;
  }

  /**
   * Get datasets
   * @return datasets
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATASETS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<LicensedDataset> getDatasets() {
    return datasets;
  }


  @JsonProperty(value = JSON_PROPERTY_DATASETS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDatasets(@javax.annotation.Nonnull List<LicensedDataset> datasets) {
    this.datasets = datasets;
  }


  /**
   * Return true if this DatasetList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetList datasetList = (DatasetList) o;
    return Objects.equals(this.datasets, datasetList.datasets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datasets);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetList {\n");
    sb.append("    datasets: ").append(toIndentedString(datasets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `datasets` to the URL query string
    if (getDatasets() != null) {
      for (int i = 0; i < getDatasets().size(); i++) {
        if (getDatasets().get(i) != null) {
          joiner.add(getDatasets().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdatasets%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

