/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.05
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * DatasetChecksums
 */
@JsonPropertyOrder({
  DatasetChecksums.JSON_PROPERTY_MD5,
  DatasetChecksums.JSON_PROPERTY_SHA1,
  DatasetChecksums.JSON_PROPERTY_SHA256,
  DatasetChecksums.JSON_PROPERTY_SHA512
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DatasetChecksums {
  public static final String JSON_PROPERTY_MD5 = "md5";
  @javax.annotation.Nullable
  private String md5;

  public static final String JSON_PROPERTY_SHA1 = "sha1";
  @javax.annotation.Nullable
  private String sha1;

  public static final String JSON_PROPERTY_SHA256 = "sha256";
  @javax.annotation.Nullable
  private String sha256;

  public static final String JSON_PROPERTY_SHA512 = "sha512";
  @javax.annotation.Nullable
  private String sha512;

  public DatasetChecksums() { 
  }

  public DatasetChecksums md5(@javax.annotation.Nullable String md5) {
    this.md5 = md5;
    return this;
  }

  /**
   * Get md5
   * @return md5
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MD5, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMd5() {
    return md5;
  }


  @JsonProperty(value = JSON_PROPERTY_MD5, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMd5(@javax.annotation.Nullable String md5) {
    this.md5 = md5;
  }


  public DatasetChecksums sha1(@javax.annotation.Nullable String sha1) {
    this.sha1 = sha1;
    return this;
  }

  /**
   * Get sha1
   * @return sha1
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHA1, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSha1() {
    return sha1;
  }


  @JsonProperty(value = JSON_PROPERTY_SHA1, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSha1(@javax.annotation.Nullable String sha1) {
    this.sha1 = sha1;
  }


  public DatasetChecksums sha256(@javax.annotation.Nullable String sha256) {
    this.sha256 = sha256;
    return this;
  }

  /**
   * Get sha256
   * @return sha256
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHA256, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSha256() {
    return sha256;
  }


  @JsonProperty(value = JSON_PROPERTY_SHA256, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSha256(@javax.annotation.Nullable String sha256) {
    this.sha256 = sha256;
  }


  public DatasetChecksums sha512(@javax.annotation.Nullable String sha512) {
    this.sha512 = sha512;
    return this;
  }

  /**
   * Get sha512
   * @return sha512
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHA512, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSha512() {
    return sha512;
  }


  @JsonProperty(value = JSON_PROPERTY_SHA512, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSha512(@javax.annotation.Nullable String sha512) {
    this.sha512 = sha512;
  }


  /**
   * Return true if this DatasetChecksums object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetChecksums datasetChecksums = (DatasetChecksums) o;
    return Objects.equals(this.md5, datasetChecksums.md5) &&
        Objects.equals(this.sha1, datasetChecksums.sha1) &&
        Objects.equals(this.sha256, datasetChecksums.sha256) &&
        Objects.equals(this.sha512, datasetChecksums.sha512);
  }

  @Override
  public int hashCode() {
    return Objects.hash(md5, sha1, sha256, sha512);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetChecksums {\n");
    sb.append("    md5: ").append(toIndentedString(md5)).append("\n");
    sb.append("    sha1: ").append(toIndentedString(sha1)).append("\n");
    sb.append("    sha256: ").append(toIndentedString(sha256)).append("\n");
    sb.append("    sha512: ").append(toIndentedString(sha512)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `md5` to the URL query string
    if (getMd5() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smd5%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMd5()))));
    }

    // add `sha1` to the URL query string
    if (getSha1() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssha1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSha1()))));
    }

    // add `sha256` to the URL query string
    if (getSha256() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssha256%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSha256()))));
    }

    // add `sha512` to the URL query string
    if (getSha512() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssha512%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSha512()))));
    }

    return joiner.toString();
  }
}

