/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.18
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * DeviceAuthorization
 */
@JsonPropertyOrder({
  DeviceAuthorization.JSON_PROPERTY_DEVICE_CODE,
  DeviceAuthorization.JSON_PROPERTY_USER_CODE,
  DeviceAuthorization.JSON_PROPERTY_VERIFICATION_URI,
  DeviceAuthorization.JSON_PROPERTY_VERIFICATION_URI_COMPLETE,
  DeviceAuthorization.JSON_PROPERTY_EXPIRES_IN,
  DeviceAuthorization.JSON_PROPERTY_INTERVAL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DeviceAuthorization {
  public static final String JSON_PROPERTY_DEVICE_CODE = "device_code";
  @javax.annotation.Nonnull
  private String deviceCode;

  public static final String JSON_PROPERTY_USER_CODE = "user_code";
  @javax.annotation.Nonnull
  private String userCode;

  public static final String JSON_PROPERTY_VERIFICATION_URI = "verification_uri";
  @javax.annotation.Nonnull
  private String verificationUri;

  public static final String JSON_PROPERTY_VERIFICATION_URI_COMPLETE = "verification_uri_complete";
  @javax.annotation.Nullable
  private String verificationUriComplete;

  public static final String JSON_PROPERTY_EXPIRES_IN = "expires_in";
  @javax.annotation.Nonnull
  private Integer expiresIn;

  public static final String JSON_PROPERTY_INTERVAL = "interval";
  @javax.annotation.Nonnull
  private Integer interval;

  public DeviceAuthorization() { 
  }

  public DeviceAuthorization deviceCode(@javax.annotation.Nonnull String deviceCode) {
    this.deviceCode = deviceCode;
    return this;
  }

  /**
   * Yours. Poll with it; never show it to anyone.
   * @return deviceCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DEVICE_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDeviceCode() {
    return deviceCode;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeviceCode(@javax.annotation.Nonnull String deviceCode) {
    this.deviceCode = deviceCode;
  }


  public DeviceAuthorization userCode(@javax.annotation.Nonnull String userCode) {
    this.userCode = userCode;
    return this;
  }

  /**
   * Short and typable. This is what the person confirms.
   * @return userCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USER_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUserCode() {
    return userCode;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserCode(@javax.annotation.Nonnull String userCode) {
    this.userCode = userCode;
  }


  public DeviceAuthorization verificationUri(@javax.annotation.Nonnull String verificationUri) {
    this.verificationUri = verificationUri;
    return this;
  }

  /**
   * Get verificationUri
   * @return verificationUri
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERIFICATION_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getVerificationUri() {
    return verificationUri;
  }


  @JsonProperty(value = JSON_PROPERTY_VERIFICATION_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVerificationUri(@javax.annotation.Nonnull String verificationUri) {
    this.verificationUri = verificationUri;
  }


  public DeviceAuthorization verificationUriComplete(@javax.annotation.Nullable String verificationUriComplete) {
    this.verificationUriComplete = verificationUriComplete;
    return this;
  }

  /**
   * The same page with the code already filled in.
   * @return verificationUriComplete
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERIFICATION_URI_COMPLETE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVerificationUriComplete() {
    return verificationUriComplete;
  }


  @JsonProperty(value = JSON_PROPERTY_VERIFICATION_URI_COMPLETE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerificationUriComplete(@javax.annotation.Nullable String verificationUriComplete) {
    this.verificationUriComplete = verificationUriComplete;
  }


  public DeviceAuthorization expiresIn(@javax.annotation.Nonnull Integer expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

  /**
   * Seconds until both codes expire.
   * @return expiresIn
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_IN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getExpiresIn() {
    return expiresIn;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_IN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiresIn(@javax.annotation.Nonnull Integer expiresIn) {
    this.expiresIn = expiresIn;
  }


  public DeviceAuthorization interval(@javax.annotation.Nonnull Integer interval) {
    this.interval = interval;
    return this;
  }

  /**
   * Seconds between polls.
   * @return interval
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INTERVAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getInterval() {
    return interval;
  }


  @JsonProperty(value = JSON_PROPERTY_INTERVAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInterval(@javax.annotation.Nonnull Integer interval) {
    this.interval = interval;
  }


  /**
   * Return true if this DeviceAuthorization object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceAuthorization deviceAuthorization = (DeviceAuthorization) o;
    return Objects.equals(this.deviceCode, deviceAuthorization.deviceCode) &&
        Objects.equals(this.userCode, deviceAuthorization.userCode) &&
        Objects.equals(this.verificationUri, deviceAuthorization.verificationUri) &&
        Objects.equals(this.verificationUriComplete, deviceAuthorization.verificationUriComplete) &&
        Objects.equals(this.expiresIn, deviceAuthorization.expiresIn) &&
        Objects.equals(this.interval, deviceAuthorization.interval);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceCode, userCode, verificationUri, verificationUriComplete, expiresIn, interval);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceAuthorization {\n");
    sb.append("    deviceCode: ").append(toIndentedString(deviceCode)).append("\n");
    sb.append("    userCode: ").append(toIndentedString(userCode)).append("\n");
    sb.append("    verificationUri: ").append(toIndentedString(verificationUri)).append("\n");
    sb.append("    verificationUriComplete: ").append(toIndentedString(verificationUriComplete)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `device_code` to the URL query string
    if (getDeviceCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdevice_code%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeviceCode()))));
    }

    // add `user_code` to the URL query string
    if (getUserCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suser_code%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserCode()))));
    }

    // add `verification_uri` to the URL query string
    if (getVerificationUri() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sverification_uri%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVerificationUri()))));
    }

    // add `verification_uri_complete` to the URL query string
    if (getVerificationUriComplete() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sverification_uri_complete%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVerificationUriComplete()))));
    }

    // add `expires_in` to the URL query string
    if (getExpiresIn() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpires_in%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiresIn()))));
    }

    // add `interval` to the URL query string
    if (getInterval() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinterval%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInterval()))));
    }

    return joiner.toString();
  }
}

