/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.04
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * Download
 */
@JsonPropertyOrder({
  Download.JSON_PROPERTY_DATASET_ID,
  Download.JSON_PROPERTY_FORMAT,
  Download.JSON_PROPERTY_OUTCOME,
  Download.JSON_PROPERTY_BYTES,
  Download.JSON_PROPERTY_CREATED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class Download {
  public static final String JSON_PROPERTY_DATASET_ID = "dataset_id";
  @javax.annotation.Nonnull
  private String datasetId;

  public static final String JSON_PROPERTY_FORMAT = "format";
  @javax.annotation.Nonnull
  private String format;

  /**
   * Gets or Sets outcome
   */
  public enum OutcomeEnum {
    OK(String.valueOf("ok")),
    
    UNAUTHORIZED(String.valueOf("unauthorized")),
    
    DENIED(String.valueOf("denied")),
    
    EXPIRED(String.valueOf("expired")),
    
    UNKNOWN(String.valueOf("unknown")),
    
    UNAVAILABLE(String.valueOf("unavailable"));

    private String value;

    OutcomeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OutcomeEnum fromValue(String value) {
      for (OutcomeEnum b : OutcomeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OUTCOME = "outcome";
  @javax.annotation.Nonnull
  private OutcomeEnum outcome;

  public static final String JSON_PROPERTY_BYTES = "bytes";
  @javax.annotation.Nullable
  private Integer bytes;

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nonnull
  private OffsetDateTime created;

  public Download() { 
  }

  public Download datasetId(@javax.annotation.Nonnull String datasetId) {
    this.datasetId = datasetId;
    return this;
  }

  /**
   * Get datasetId
   * @return datasetId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATASET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDatasetId() {
    return datasetId;
  }


  @JsonProperty(value = JSON_PROPERTY_DATASET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDatasetId(@javax.annotation.Nonnull String datasetId) {
    this.datasetId = datasetId;
  }


  public Download format(@javax.annotation.Nonnull String format) {
    this.format = format;
    return this;
  }

  /**
   * Get format
   * @return format
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFormat(@javax.annotation.Nonnull String format) {
    this.format = format;
  }


  public Download outcome(@javax.annotation.Nonnull OutcomeEnum outcome) {
    this.outcome = outcome;
    return this;
  }

  /**
   * Get outcome
   * @return outcome
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTCOME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OutcomeEnum getOutcome() {
    return outcome;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTCOME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutcome(@javax.annotation.Nonnull OutcomeEnum outcome) {
    this.outcome = outcome;
  }


  public Download bytes(@javax.annotation.Nullable Integer bytes) {
    this.bytes = bytes;
    return this;
  }

  /**
   * Get bytes
   * @return bytes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BYTES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getBytes() {
    return bytes;
  }


  @JsonProperty(value = JSON_PROPERTY_BYTES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBytes(@javax.annotation.Nullable Integer bytes) {
    this.bytes = bytes;
  }


  public Download created(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreated() {
    return created;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
  }


  /**
   * Return true if this Download object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Download download = (Download) o;
    return Objects.equals(this.datasetId, download.datasetId) &&
        Objects.equals(this.format, download.format) &&
        Objects.equals(this.outcome, download.outcome) &&
        Objects.equals(this.bytes, download.bytes) &&
        Objects.equals(this.created, download.created);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datasetId, format, outcome, bytes, created);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Download {\n");
    sb.append("    datasetId: ").append(toIndentedString(datasetId)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    bytes: ").append(toIndentedString(bytes)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `dataset_id` to the URL query string
    if (getDatasetId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdataset_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDatasetId()))));
    }

    // add `format` to the URL query string
    if (getFormat() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sformat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFormat()))));
    }

    // add `outcome` to the URL query string
    if (getOutcome() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soutcome%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOutcome()))));
    }

    // add `bytes` to the URL query string
    if (getBytes() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbytes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBytes()))));
    }

    // add `created` to the URL query string
    if (getCreated() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreated()))));
    }

    return joiner.toString();
  }
}

