/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.18
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * The credential itself. The key is never echoed - only its id, which is what the console shows and what you can act on. 
 */
@JsonPropertyOrder({
  EntitlementApikey.JSON_PROPERTY_ID,
  EntitlementApikey.JSON_PROPERTY_EXPIRES,
  EntitlementApikey.JSON_PROPERTY_ALLOWED_CIDRS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class EntitlementApikey {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_EXPIRES = "expires";
  @javax.annotation.Nullable
  private OffsetDateTime expires;

  public static final String JSON_PROPERTY_ALLOWED_CIDRS = "allowed_cidrs";
  @javax.annotation.Nonnull
  private List<String> allowedCidrs = new ArrayList<>();

  public EntitlementApikey() { 
  }

  public EntitlementApikey id(@javax.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public EntitlementApikey expires(@javax.annotation.Nullable OffsetDateTime expires) {
    this.expires = expires;
    return this;
  }

  /**
   * Null for a key with no end date, which is the normal case.
   * @return expires
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRES, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getExpires() {
    return expires;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpires(@javax.annotation.Nullable OffsetDateTime expires) {
    this.expires = expires;
  }


  public EntitlementApikey allowedCidrs(@javax.annotation.Nonnull List<String> allowedCidrs) {
    this.allowedCidrs = allowedCidrs;
    return this;
  }

  public EntitlementApikey addAllowedCidrsItem(String allowedCidrsItem) {
    if (this.allowedCidrs == null) {
      this.allowedCidrs = new ArrayList<>();
    }
    this.allowedCidrs.add(allowedCidrsItem);
    return this;
  }

  /**
   * The source addresses this key may be used from. EMPTY means unrestricted, never \&quot;deny all\&quot;. 
   * @return allowedCidrs
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ALLOWED_CIDRS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getAllowedCidrs() {
    return allowedCidrs;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOWED_CIDRS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAllowedCidrs(@javax.annotation.Nonnull List<String> allowedCidrs) {
    this.allowedCidrs = allowedCidrs;
  }


  /**
   * Return true if this EntitlementApikey object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntitlementApikey entitlementApikey = (EntitlementApikey) o;
    return Objects.equals(this.id, entitlementApikey.id) &&
        Objects.equals(this.expires, entitlementApikey.expires) &&
        Objects.equals(this.allowedCidrs, entitlementApikey.allowedCidrs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, expires, allowedCidrs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntitlementApikey {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    allowedCidrs: ").append(toIndentedString(allowedCidrs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `expires` to the URL query string
    if (getExpires() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpires%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpires()))));
    }

    // add `allowed_cidrs` to the URL query string
    if (getAllowedCidrs() != null) {
      for (int i = 0; i < getAllowedCidrs().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sallowed_cidrs%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAllowedCidrs().get(i)))));
      }
    }

    return joiner.toString();
  }
}

