/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.15
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * EntitlementUsage
 */
@JsonPropertyOrder({
  EntitlementUsage.JSON_PROPERTY_REQUESTS,
  EntitlementUsage.JSON_PROPERTY_QUOTA,
  EntitlementUsage.JSON_PROPERTY_HARD_LIMIT,
  EntitlementUsage.JSON_PROPERTY_WINDOW_START,
  EntitlementUsage.JSON_PROPERTY_WINDOW_END
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class EntitlementUsage {
  public static final String JSON_PROPERTY_REQUESTS = "requests";
  @javax.annotation.Nonnull
  private Long requests;

  public static final String JSON_PROPERTY_QUOTA = "quota";
  @javax.annotation.Nonnull
  private Long quota;

  public static final String JSON_PROPERTY_HARD_LIMIT = "hard_limit";
  @javax.annotation.Nullable
  private Long hardLimit;

  public static final String JSON_PROPERTY_WINDOW_START = "window_start";
  @javax.annotation.Nonnull
  private OffsetDateTime windowStart;

  public static final String JSON_PROPERTY_WINDOW_END = "window_end";
  @javax.annotation.Nonnull
  private OffsetDateTime windowEnd;

  public EntitlementUsage() { 
  }

  public EntitlementUsage requests(@javax.annotation.Nonnull Long requests) {
    this.requests = requests;
    return this;
  }

  /**
   * Requests counted in the current window. The same number the lookup API gates on, and it can lag by a few seconds. 
   * @return requests
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUESTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getRequests() {
    return requests;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUESTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequests(@javax.annotation.Nonnull Long requests) {
    this.requests = requests;
  }


  public EntitlementUsage quota(@javax.annotation.Nonnull Long quota) {
    this.quota = quota;
    return this;
  }

  /**
   * What the plan includes. Zero on a plan that includes none.
   * @return quota
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUOTA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getQuota() {
    return quota;
  }


  @JsonProperty(value = JSON_PROPERTY_QUOTA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuota(@javax.annotation.Nonnull Long quota) {
    this.quota = quota;
  }


  public EntitlementUsage hardLimit(@javax.annotation.Nullable Long hardLimit) {
    this.hardLimit = hardLimit;
    return this;
  }

  /**
   * Where we stop serving. NULL means never, which is the normal state of an uncapped paid plan and is not the same as zero. Above the quota and below this, requests are served and billed as overage. 
   * @return hardLimit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HARD_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getHardLimit() {
    return hardLimit;
  }


  @JsonProperty(value = JSON_PROPERTY_HARD_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHardLimit(@javax.annotation.Nullable Long hardLimit) {
    this.hardLimit = hardLimit;
  }


  public EntitlementUsage windowStart(@javax.annotation.Nonnull OffsetDateTime windowStart) {
    this.windowStart = windowStart;
    return this;
  }

  /**
   * When the current allowance period began.
   * @return windowStart
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WINDOW_START, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getWindowStart() {
    return windowStart;
  }


  @JsonProperty(value = JSON_PROPERTY_WINDOW_START, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWindowStart(@javax.annotation.Nonnull OffsetDateTime windowStart) {
    this.windowStart = windowStart;
  }


  public EntitlementUsage windowEnd(@javax.annotation.Nonnull OffsetDateTime windowEnd) {
    this.windowEnd = windowEnd;
    return this;
  }

  /**
   * When the allowance next resets.
   * @return windowEnd
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WINDOW_END, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getWindowEnd() {
    return windowEnd;
  }


  @JsonProperty(value = JSON_PROPERTY_WINDOW_END, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWindowEnd(@javax.annotation.Nonnull OffsetDateTime windowEnd) {
    this.windowEnd = windowEnd;
  }


  /**
   * Return true if this EntitlementUsage object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntitlementUsage entitlementUsage = (EntitlementUsage) o;
    return Objects.equals(this.requests, entitlementUsage.requests) &&
        Objects.equals(this.quota, entitlementUsage.quota) &&
        Objects.equals(this.hardLimit, entitlementUsage.hardLimit) &&
        Objects.equals(this.windowStart, entitlementUsage.windowStart) &&
        Objects.equals(this.windowEnd, entitlementUsage.windowEnd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requests, quota, hardLimit, windowStart, windowEnd);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntitlementUsage {\n");
    sb.append("    requests: ").append(toIndentedString(requests)).append("\n");
    sb.append("    quota: ").append(toIndentedString(quota)).append("\n");
    sb.append("    hardLimit: ").append(toIndentedString(hardLimit)).append("\n");
    sb.append("    windowStart: ").append(toIndentedString(windowStart)).append("\n");
    sb.append("    windowEnd: ").append(toIndentedString(windowEnd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `requests` to the URL query string
    if (getRequests() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequests%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequests()))));
    }

    // add `quota` to the URL query string
    if (getQuota() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squota%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuota()))));
    }

    // add `hard_limit` to the URL query string
    if (getHardLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shard_limit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHardLimit()))));
    }

    // add `window_start` to the URL query string
    if (getWindowStart() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swindow_start%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWindowStart()))));
    }

    // add `window_end` to the URL query string
    if (getWindowEnd() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swindow_end%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWindowEnd()))));
    }

    return joiner.toString();
  }
}

