/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.16
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * EntitlementPlan
 */
@JsonPropertyOrder({
  EntitlementPlan.JSON_PROPERTY_KEY,
  EntitlementPlan.JSON_PROPERTY_TIER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class EntitlementPlan {
  public static final String JSON_PROPERTY_KEY = "key";
  @javax.annotation.Nonnull
  private String key;

  /**
   * The field tier, which decides how much of a lookup answer comes back. What each tier includes is documented on the lookup endpoint rather than repeated here, so there is one place it can be wrong. 
   */
  public enum TierEnum {
    FREE(String.valueOf("free")),
    
    STARTER(String.valueOf("starter")),
    
    SCALE(String.valueOf("scale")),
    
    MAX(String.valueOf("max"));

    private String value;

    TierEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TierEnum fromValue(String value) {
      for (TierEnum b : TierEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TIER = "tier";
  @javax.annotation.Nonnull
  private TierEnum tier;

  public EntitlementPlan() { 
  }

  public EntitlementPlan key(@javax.annotation.Nonnull String key) {
    this.key = key;
    return this;
  }

  /**
   * The plan the organization is on.
   * @return key
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(@javax.annotation.Nonnull String key) {
    this.key = key;
  }


  public EntitlementPlan tier(@javax.annotation.Nonnull TierEnum tier) {
    this.tier = tier;
    return this;
  }

  /**
   * The field tier, which decides how much of a lookup answer comes back. What each tier includes is documented on the lookup endpoint rather than repeated here, so there is one place it can be wrong. 
   * @return tier
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TierEnum getTier() {
    return tier;
  }


  @JsonProperty(value = JSON_PROPERTY_TIER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTier(@javax.annotation.Nonnull TierEnum tier) {
    this.tier = tier;
  }


  /**
   * Return true if this EntitlementPlan object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntitlementPlan entitlementPlan = (EntitlementPlan) o;
    return Objects.equals(this.key, entitlementPlan.key) &&
        Objects.equals(this.tier, entitlementPlan.tier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, tier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntitlementPlan {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    tier: ").append(toIndentedString(tier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `key` to the URL query string
    if (getKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKey()))));
    }

    // add `tier` to the URL query string
    if (getTier() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stier%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTier()))));
    }

    return joiner.toString();
  }
}

