/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.04
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.vpndetection.model.DatasetFormatSize;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * LicensedVersion
 */
@JsonPropertyOrder({
  LicensedVersion.JSON_PROPERTY_ID,
  LicensedVersion.JSON_PROPERTY_VERSION,
  LicensedVersion.JSON_PROPERTY_SUMMARY,
  LicensedVersion.JSON_PROPERTY_FORMATS,
  LicensedVersion.JSON_PROPERTY_SAMPLE_FORMATS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class LicensedVersion {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nonnull
  private Integer version;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @javax.annotation.Nullable
  private String summary;

  public static final String JSON_PROPERTY_FORMATS = "formats";
  @javax.annotation.Nonnull
  private List<DatasetFormatSize> formats = new ArrayList<>();

  /**
   * Gets or Sets sampleFormats
   */
  public enum SampleFormatsEnum {
    CSVGZ(String.valueOf("csvgz")),
    
    MMDB(String.valueOf("mmdb"));

    private String value;

    SampleFormatsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SampleFormatsEnum fromValue(String value) {
      for (SampleFormatsEnum b : SampleFormatsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SAMPLE_FORMATS = "sampleFormats";
  @javax.annotation.Nullable
  private List<SampleFormatsEnum> sampleFormats = new ArrayList<>();

  public LicensedVersion() { 
  }

  public LicensedVersion id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * The versioned dataset id, e.g. &#x60;vpn_ip_v1&#x60;. Pass this to download.
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public LicensedVersion version(@javax.annotation.Nonnull Integer version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@javax.annotation.Nonnull Integer version) {
    this.version = version;
  }


  public LicensedVersion summary(@javax.annotation.Nullable String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummary(@javax.annotation.Nullable String summary) {
    this.summary = summary;
  }


  public LicensedVersion formats(@javax.annotation.Nonnull List<DatasetFormatSize> formats) {
    this.formats = formats;
    return this;
  }

  public LicensedVersion addFormatsItem(DatasetFormatSize formatsItem) {
    if (this.formats == null) {
      this.formats = new ArrayList<>();
    }
    this.formats.add(formatsItem);
    return this;
  }

  /**
   * Get formats
   * @return formats
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FORMATS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<DatasetFormatSize> getFormats() {
    return formats;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMATS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFormats(@javax.annotation.Nonnull List<DatasetFormatSize> formats) {
    this.formats = formats;
  }


  public LicensedVersion sampleFormats(@javax.annotation.Nullable List<SampleFormatsEnum> sampleFormats) {
    this.sampleFormats = sampleFormats;
    return this;
  }

  public LicensedVersion addSampleFormatsItem(SampleFormatsEnum sampleFormatsItem) {
    if (this.sampleFormats == null) {
      this.sampleFormats = new ArrayList<>();
    }
    this.sampleFormats.add(sampleFormatsItem);
    return this;
  }

  /**
   * The formats an evaluation sample is published in, if any.
   * @return sampleFormats
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SAMPLE_FORMATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SampleFormatsEnum> getSampleFormats() {
    return sampleFormats;
  }


  @JsonProperty(value = JSON_PROPERTY_SAMPLE_FORMATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSampleFormats(@javax.annotation.Nullable List<SampleFormatsEnum> sampleFormats) {
    this.sampleFormats = sampleFormats;
  }


  /**
   * Return true if this LicensedVersion object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicensedVersion licensedVersion = (LicensedVersion) o;
    return Objects.equals(this.id, licensedVersion.id) &&
        Objects.equals(this.version, licensedVersion.version) &&
        Objects.equals(this.summary, licensedVersion.summary) &&
        Objects.equals(this.formats, licensedVersion.formats) &&
        Objects.equals(this.sampleFormats, licensedVersion.sampleFormats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, version, summary, formats, sampleFormats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicensedVersion {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    formats: ").append(toIndentedString(formats)).append("\n");
    sb.append("    sampleFormats: ").append(toIndentedString(sampleFormats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `version` to the URL query string
    if (getVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sversion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersion()))));
    }

    // add `summary` to the URL query string
    if (getSummary() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssummary%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSummary()))));
    }

    // add `formats` to the URL query string
    if (getFormats() != null) {
      for (int i = 0; i < getFormats().size(); i++) {
        if (getFormats().get(i) != null) {
          joiner.add(getFormats().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sformats%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `sampleFormats` to the URL query string
    if (getSampleFormats() != null) {
      for (int i = 0; i < getSampleFormats().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssampleFormats%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getSampleFormats().get(i)))));
      }
    }

    return joiner.toString();
  }
}

