/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.03
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.vpndetection.model.DatasetFormatSize;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * LicensedDataset
 */
@JsonPropertyOrder({
  LicensedDataset.JSON_PROPERTY_ID,
  LicensedDataset.JSON_PROPERTY_NAME,
  LicensedDataset.JSON_PROPERTY_SUMMARY,
  LicensedDataset.JSON_PROPERTY_RETIRED,
  LicensedDataset.JSON_PROPERTY_REDISTRIBUTION,
  LicensedDataset.JSON_PROPERTY_STARTS,
  LicensedDataset.JSON_PROPERTY_EXPIRES,
  LicensedDataset.JSON_PROPERTY_IN_TERM,
  LicensedDataset.JSON_PROPERTY_FORMATS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class LicensedDataset {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @javax.annotation.Nullable
  private String summary;

  public static final String JSON_PROPERTY_RETIRED = "retired";
  @javax.annotation.Nullable
  private Boolean retired;

  /**
   * What your license permits you to do with the data
   */
  public enum RedistributionEnum {
    EVALUATION(String.valueOf("evaluation")),
    
    INTERNAL(String.valueOf("internal")),
    
    REDISTRIBUTE(String.valueOf("redistribute"));

    private String value;

    RedistributionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RedistributionEnum fromValue(String value) {
      for (RedistributionEnum b : RedistributionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REDISTRIBUTION = "redistribution";
  @javax.annotation.Nonnull
  private RedistributionEnum redistribution;

  public static final String JSON_PROPERTY_STARTS = "starts";
  @javax.annotation.Nullable
  private OffsetDateTime starts;

  public static final String JSON_PROPERTY_EXPIRES = "expires";
  @javax.annotation.Nullable
  private OffsetDateTime expires;

  public static final String JSON_PROPERTY_IN_TERM = "in_term";
  @javax.annotation.Nonnull
  private Boolean inTerm;

  public static final String JSON_PROPERTY_FORMATS = "formats";
  @javax.annotation.Nonnull
  private List<DatasetFormatSize> formats = new ArrayList<>();

  public LicensedDataset() { 
  }

  public LicensedDataset id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public LicensedDataset name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public LicensedDataset summary(@javax.annotation.Nullable String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummary(@javax.annotation.Nullable String summary) {
    this.summary = summary;
  }


  public LicensedDataset retired(@javax.annotation.Nullable Boolean retired) {
    this.retired = retired;
    return this;
  }

  /**
   * Licensed but no longer published. Talk to us.
   * @return retired
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getRetired() {
    return retired;
  }


  @JsonProperty(value = JSON_PROPERTY_RETIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetired(@javax.annotation.Nullable Boolean retired) {
    this.retired = retired;
  }


  public LicensedDataset redistribution(@javax.annotation.Nonnull RedistributionEnum redistribution) {
    this.redistribution = redistribution;
    return this;
  }

  /**
   * What your license permits you to do with the data
   * @return redistribution
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REDISTRIBUTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RedistributionEnum getRedistribution() {
    return redistribution;
  }


  @JsonProperty(value = JSON_PROPERTY_REDISTRIBUTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRedistribution(@javax.annotation.Nonnull RedistributionEnum redistribution) {
    this.redistribution = redistribution;
  }


  public LicensedDataset starts(@javax.annotation.Nullable OffsetDateTime starts) {
    this.starts = starts;
    return this;
  }

  /**
   * Get starts
   * @return starts
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STARTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getStarts() {
    return starts;
  }


  @JsonProperty(value = JSON_PROPERTY_STARTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStarts(@javax.annotation.Nullable OffsetDateTime starts) {
    this.starts = starts;
  }


  public LicensedDataset expires(@javax.annotation.Nullable OffsetDateTime expires) {
    this.expires = expires;
    return this;
  }

  /**
   * Get expires
   * @return expires
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getExpires() {
    return expires;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpires(@javax.annotation.Nullable OffsetDateTime expires) {
    this.expires = expires;
  }


  public LicensedDataset inTerm(@javax.annotation.Nonnull Boolean inTerm) {
    this.inTerm = inTerm;
    return this;
  }

  /**
   * False when the license has lapsed; downloads are refused
   * @return inTerm
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IN_TERM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getInTerm() {
    return inTerm;
  }


  @JsonProperty(value = JSON_PROPERTY_IN_TERM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInTerm(@javax.annotation.Nonnull Boolean inTerm) {
    this.inTerm = inTerm;
  }


  public LicensedDataset formats(@javax.annotation.Nonnull List<DatasetFormatSize> formats) {
    this.formats = formats;
    return this;
  }

  public LicensedDataset addFormatsItem(DatasetFormatSize formatsItem) {
    if (this.formats == null) {
      this.formats = new ArrayList<>();
    }
    this.formats.add(formatsItem);
    return this;
  }

  /**
   * Get formats
   * @return formats
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FORMATS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<DatasetFormatSize> getFormats() {
    return formats;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMATS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFormats(@javax.annotation.Nonnull List<DatasetFormatSize> formats) {
    this.formats = formats;
  }


  /**
   * Return true if this LicensedDataset object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicensedDataset licensedDataset = (LicensedDataset) o;
    return Objects.equals(this.id, licensedDataset.id) &&
        Objects.equals(this.name, licensedDataset.name) &&
        Objects.equals(this.summary, licensedDataset.summary) &&
        Objects.equals(this.retired, licensedDataset.retired) &&
        Objects.equals(this.redistribution, licensedDataset.redistribution) &&
        Objects.equals(this.starts, licensedDataset.starts) &&
        Objects.equals(this.expires, licensedDataset.expires) &&
        Objects.equals(this.inTerm, licensedDataset.inTerm) &&
        Objects.equals(this.formats, licensedDataset.formats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, summary, retired, redistribution, starts, expires, inTerm, formats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicensedDataset {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    retired: ").append(toIndentedString(retired)).append("\n");
    sb.append("    redistribution: ").append(toIndentedString(redistribution)).append("\n");
    sb.append("    starts: ").append(toIndentedString(starts)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    inTerm: ").append(toIndentedString(inTerm)).append("\n");
    sb.append("    formats: ").append(toIndentedString(formats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `summary` to the URL query string
    if (getSummary() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssummary%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSummary()))));
    }

    // add `retired` to the URL query string
    if (getRetired() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sretired%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetired()))));
    }

    // add `redistribution` to the URL query string
    if (getRedistribution() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sredistribution%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRedistribution()))));
    }

    // add `starts` to the URL query string
    if (getStarts() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstarts%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStarts()))));
    }

    // add `expires` to the URL query string
    if (getExpires() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpires%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpires()))));
    }

    // add `in_term` to the URL query string
    if (getInTerm() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sin_term%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInTerm()))));
    }

    // add `formats` to the URL query string
    if (getFormats() != null) {
      for (int i = 0; i < getFormats().size(); i++) {
        if (getFormats().get(i) != null) {
          joiner.add(getFormats().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sformats%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

