/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.05
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.vpndetection.model.ClassDetail;
import io.vpndetection.model.ProxyDetail;
import io.vpndetection.model.VpnDetail;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * The union of every plan&#39;s answer. Only &#x60;ip&#x60; and &#x60;is_vpn&#x60; are guaranteed; each remaining field is present when your plan includes it, and absent otherwise. A client that must work across plans should treat an absent flag as unknown rather than as &#x60;false&#x60;. 
 */
@JsonPropertyOrder({
  LookupResponse.JSON_PROPERTY_IP,
  LookupResponse.JSON_PROPERTY_IS_VPN,
  LookupResponse.JSON_PROPERTY_IS_HOSTING,
  LookupResponse.JSON_PROPERTY_IS_RELAY,
  LookupResponse.JSON_PROPERTY_IS_TOR,
  LookupResponse.JSON_PROPERTY_IS_CDN,
  LookupResponse.JSON_PROPERTY_IS_RESPROXY,
  LookupResponse.JSON_PROPERTY_IS_DCPROXY,
  LookupResponse.JSON_PROPERTY_IS_MOBPROXY,
  LookupResponse.JSON_PROPERTY_VPN,
  LookupResponse.JSON_PROPERTY_HOSTING,
  LookupResponse.JSON_PROPERTY_RELAY,
  LookupResponse.JSON_PROPERTY_TOR,
  LookupResponse.JSON_PROPERTY_CDN,
  LookupResponse.JSON_PROPERTY_RESPROXY,
  LookupResponse.JSON_PROPERTY_DCPROXY,
  LookupResponse.JSON_PROPERTY_MOBPROXY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class LookupResponse {
  public static final String JSON_PROPERTY_IP = "ip";
  @javax.annotation.Nonnull
  private String ip;

  public static final String JSON_PROPERTY_IS_VPN = "is_vpn";
  @javax.annotation.Nonnull
  private Boolean isVpn;

  public static final String JSON_PROPERTY_IS_HOSTING = "is_hosting";
  @javax.annotation.Nullable
  private Boolean isHosting;

  public static final String JSON_PROPERTY_IS_RELAY = "is_relay";
  @javax.annotation.Nullable
  private Boolean isRelay;

  public static final String JSON_PROPERTY_IS_TOR = "is_tor";
  @javax.annotation.Nullable
  private Boolean isTor;

  public static final String JSON_PROPERTY_IS_CDN = "is_cdn";
  @javax.annotation.Nullable
  private Boolean isCdn;

  public static final String JSON_PROPERTY_IS_RESPROXY = "is_resproxy";
  @javax.annotation.Nullable
  private Boolean isResproxy;

  public static final String JSON_PROPERTY_IS_DCPROXY = "is_dcproxy";
  @javax.annotation.Nullable
  private Boolean isDcproxy;

  public static final String JSON_PROPERTY_IS_MOBPROXY = "is_mobproxy";
  @javax.annotation.Nullable
  private Boolean isMobproxy;

  public static final String JSON_PROPERTY_VPN = "vpn";
  @javax.annotation.Nullable
  private VpnDetail vpn;

  public static final String JSON_PROPERTY_HOSTING = "hosting";
  @javax.annotation.Nullable
  private ClassDetail hosting;

  public static final String JSON_PROPERTY_RELAY = "relay";
  @javax.annotation.Nullable
  private ClassDetail relay;

  public static final String JSON_PROPERTY_TOR = "tor";
  @javax.annotation.Nullable
  private ClassDetail tor;

  public static final String JSON_PROPERTY_CDN = "cdn";
  @javax.annotation.Nullable
  private ClassDetail cdn;

  public static final String JSON_PROPERTY_RESPROXY = "resproxy";
  @javax.annotation.Nullable
  private ProxyDetail resproxy;

  public static final String JSON_PROPERTY_DCPROXY = "dcproxy";
  @javax.annotation.Nullable
  private ProxyDetail dcproxy;

  public static final String JSON_PROPERTY_MOBPROXY = "mobproxy";
  @javax.annotation.Nullable
  private ProxyDetail mobproxy;

  public LookupResponse() { 
  }

  public LookupResponse ip(@javax.annotation.Nonnull String ip) {
    this.ip = ip;
    return this;
  }

  /**
   * The address that was looked up, normalized.
   * @return ip
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getIp() {
    return ip;
  }


  @JsonProperty(value = JSON_PROPERTY_IP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIp(@javax.annotation.Nonnull String ip) {
    this.ip = ip;
  }


  public LookupResponse isVpn(@javax.annotation.Nonnull Boolean isVpn) {
    this.isVpn = isVpn;
    return this;
  }

  /**
   * Whether the address is VPN infrastructure. Keys off presence in the VPN dataset, so an unattributed range with no provider is still &#x60;true&#x60;. 
   * @return isVpn
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IS_VPN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getIsVpn() {
    return isVpn;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_VPN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsVpn(@javax.annotation.Nonnull Boolean isVpn) {
    this.isVpn = isVpn;
  }


  public LookupResponse isHosting(@javax.annotation.Nullable Boolean isHosting) {
    this.isHosting = isHosting;
    return this;
  }

  /**
   * Whether the address belongs to a hosting or cloud provider. Starter and above.
   * @return isHosting
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_HOSTING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsHosting() {
    return isHosting;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_HOSTING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsHosting(@javax.annotation.Nullable Boolean isHosting) {
    this.isHosting = isHosting;
  }


  public LookupResponse isRelay(@javax.annotation.Nullable Boolean isRelay) {
    this.isRelay = isRelay;
    return this;
  }

  /**
   * Whether the address is a privacy relay egress. Starter and above.
   * @return isRelay
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_RELAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsRelay() {
    return isRelay;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_RELAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsRelay(@javax.annotation.Nullable Boolean isRelay) {
    this.isRelay = isRelay;
  }


  public LookupResponse isTor(@javax.annotation.Nullable Boolean isTor) {
    this.isTor = isTor;
    return this;
  }

  /**
   * Whether the address is a Tor node. Starter and above.
   * @return isTor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_TOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsTor() {
    return isTor;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_TOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsTor(@javax.annotation.Nullable Boolean isTor) {
    this.isTor = isTor;
  }


  public LookupResponse isCdn(@javax.annotation.Nullable Boolean isCdn) {
    this.isCdn = isCdn;
    return this;
  }

  /**
   * Whether the address belongs to a CDN. Starter and above.
   * @return isCdn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_CDN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsCdn() {
    return isCdn;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_CDN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsCdn(@javax.annotation.Nullable Boolean isCdn) {
    this.isCdn = isCdn;
  }


  public LookupResponse isResproxy(@javax.annotation.Nullable Boolean isResproxy) {
    this.isResproxy = isResproxy;
    return this;
  }

  /**
   * Whether the address was seen in a residential proxy pool. Max only.
   * @return isResproxy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_RESPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsResproxy() {
    return isResproxy;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_RESPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsResproxy(@javax.annotation.Nullable Boolean isResproxy) {
    this.isResproxy = isResproxy;
  }


  public LookupResponse isDcproxy(@javax.annotation.Nullable Boolean isDcproxy) {
    this.isDcproxy = isDcproxy;
    return this;
  }

  /**
   * Whether the address was seen in a datacenter proxy pool. Max only.
   * @return isDcproxy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_DCPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsDcproxy() {
    return isDcproxy;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_DCPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDcproxy(@javax.annotation.Nullable Boolean isDcproxy) {
    this.isDcproxy = isDcproxy;
  }


  public LookupResponse isMobproxy(@javax.annotation.Nullable Boolean isMobproxy) {
    this.isMobproxy = isMobproxy;
    return this;
  }

  /**
   * Whether the address was seen in a mobile proxy pool. Max only.
   * @return isMobproxy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_MOBPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsMobproxy() {
    return isMobproxy;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_MOBPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsMobproxy(@javax.annotation.Nullable Boolean isMobproxy) {
    this.isMobproxy = isMobproxy;
  }


  public LookupResponse vpn(@javax.annotation.Nullable VpnDetail vpn) {
    this.vpn = vpn;
    return this;
  }

  /**
   * Detail for &#x60;is_vpn&#x60;. Empty when &#x60;is_vpn&#x60; is false. Starter and above. 
   * @return vpn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VPN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public VpnDetail getVpn() {
    return vpn;
  }


  @JsonProperty(value = JSON_PROPERTY_VPN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVpn(@javax.annotation.Nullable VpnDetail vpn) {
    this.vpn = vpn;
  }


  public LookupResponse hosting(@javax.annotation.Nullable ClassDetail hosting) {
    this.hosting = hosting;
    return this;
  }

  /**
   * Detail for &#x60;is_hosting&#x60;. Empty when false. Scale and above.
   * @return hosting
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOSTING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ClassDetail getHosting() {
    return hosting;
  }


  @JsonProperty(value = JSON_PROPERTY_HOSTING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHosting(@javax.annotation.Nullable ClassDetail hosting) {
    this.hosting = hosting;
  }


  public LookupResponse relay(@javax.annotation.Nullable ClassDetail relay) {
    this.relay = relay;
    return this;
  }

  /**
   * Detail for &#x60;is_relay&#x60;. Empty when false. Scale and above.
   * @return relay
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RELAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ClassDetail getRelay() {
    return relay;
  }


  @JsonProperty(value = JSON_PROPERTY_RELAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelay(@javax.annotation.Nullable ClassDetail relay) {
    this.relay = relay;
  }


  public LookupResponse tor(@javax.annotation.Nullable ClassDetail tor) {
    this.tor = tor;
    return this;
  }

  /**
   * Detail for &#x60;is_tor&#x60;. Empty when false. Scale and above. The tor dataset carries no provider, so &#x60;provider&#x60; is always an empty string. 
   * @return tor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ClassDetail getTor() {
    return tor;
  }


  @JsonProperty(value = JSON_PROPERTY_TOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTor(@javax.annotation.Nullable ClassDetail tor) {
    this.tor = tor;
  }


  public LookupResponse cdn(@javax.annotation.Nullable ClassDetail cdn) {
    this.cdn = cdn;
    return this;
  }

  /**
   * Detail for &#x60;is_cdn&#x60;. Empty when false. Scale and above.
   * @return cdn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CDN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ClassDetail getCdn() {
    return cdn;
  }


  @JsonProperty(value = JSON_PROPERTY_CDN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCdn(@javax.annotation.Nullable ClassDetail cdn) {
    this.cdn = cdn;
  }


  public LookupResponse resproxy(@javax.annotation.Nullable ProxyDetail resproxy) {
    this.resproxy = resproxy;
    return this;
  }

  /**
   * Detail for &#x60;is_resproxy&#x60;. Empty when false. Max only.
   * @return resproxy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProxyDetail getResproxy() {
    return resproxy;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResproxy(@javax.annotation.Nullable ProxyDetail resproxy) {
    this.resproxy = resproxy;
  }


  public LookupResponse dcproxy(@javax.annotation.Nullable ProxyDetail dcproxy) {
    this.dcproxy = dcproxy;
    return this;
  }

  /**
   * Detail for &#x60;is_dcproxy&#x60;. Empty when false. Max only.
   * @return dcproxy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DCPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProxyDetail getDcproxy() {
    return dcproxy;
  }


  @JsonProperty(value = JSON_PROPERTY_DCPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDcproxy(@javax.annotation.Nullable ProxyDetail dcproxy) {
    this.dcproxy = dcproxy;
  }


  public LookupResponse mobproxy(@javax.annotation.Nullable ProxyDetail mobproxy) {
    this.mobproxy = mobproxy;
    return this;
  }

  /**
   * Detail for &#x60;is_mobproxy&#x60;. Empty when false. Max only.
   * @return mobproxy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MOBPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProxyDetail getMobproxy() {
    return mobproxy;
  }


  @JsonProperty(value = JSON_PROPERTY_MOBPROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMobproxy(@javax.annotation.Nullable ProxyDetail mobproxy) {
    this.mobproxy = mobproxy;
  }


  /**
   * Return true if this LookupResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LookupResponse lookupResponse = (LookupResponse) o;
    return Objects.equals(this.ip, lookupResponse.ip) &&
        Objects.equals(this.isVpn, lookupResponse.isVpn) &&
        Objects.equals(this.isHosting, lookupResponse.isHosting) &&
        Objects.equals(this.isRelay, lookupResponse.isRelay) &&
        Objects.equals(this.isTor, lookupResponse.isTor) &&
        Objects.equals(this.isCdn, lookupResponse.isCdn) &&
        Objects.equals(this.isResproxy, lookupResponse.isResproxy) &&
        Objects.equals(this.isDcproxy, lookupResponse.isDcproxy) &&
        Objects.equals(this.isMobproxy, lookupResponse.isMobproxy) &&
        Objects.equals(this.vpn, lookupResponse.vpn) &&
        Objects.equals(this.hosting, lookupResponse.hosting) &&
        Objects.equals(this.relay, lookupResponse.relay) &&
        Objects.equals(this.tor, lookupResponse.tor) &&
        Objects.equals(this.cdn, lookupResponse.cdn) &&
        Objects.equals(this.resproxy, lookupResponse.resproxy) &&
        Objects.equals(this.dcproxy, lookupResponse.dcproxy) &&
        Objects.equals(this.mobproxy, lookupResponse.mobproxy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ip, isVpn, isHosting, isRelay, isTor, isCdn, isResproxy, isDcproxy, isMobproxy, vpn, hosting, relay, tor, cdn, resproxy, dcproxy, mobproxy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LookupResponse {\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    isVpn: ").append(toIndentedString(isVpn)).append("\n");
    sb.append("    isHosting: ").append(toIndentedString(isHosting)).append("\n");
    sb.append("    isRelay: ").append(toIndentedString(isRelay)).append("\n");
    sb.append("    isTor: ").append(toIndentedString(isTor)).append("\n");
    sb.append("    isCdn: ").append(toIndentedString(isCdn)).append("\n");
    sb.append("    isResproxy: ").append(toIndentedString(isResproxy)).append("\n");
    sb.append("    isDcproxy: ").append(toIndentedString(isDcproxy)).append("\n");
    sb.append("    isMobproxy: ").append(toIndentedString(isMobproxy)).append("\n");
    sb.append("    vpn: ").append(toIndentedString(vpn)).append("\n");
    sb.append("    hosting: ").append(toIndentedString(hosting)).append("\n");
    sb.append("    relay: ").append(toIndentedString(relay)).append("\n");
    sb.append("    tor: ").append(toIndentedString(tor)).append("\n");
    sb.append("    cdn: ").append(toIndentedString(cdn)).append("\n");
    sb.append("    resproxy: ").append(toIndentedString(resproxy)).append("\n");
    sb.append("    dcproxy: ").append(toIndentedString(dcproxy)).append("\n");
    sb.append("    mobproxy: ").append(toIndentedString(mobproxy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `ip` to the URL query string
    if (getIp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sip%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIp()))));
    }

    // add `is_vpn` to the URL query string
    if (getIsVpn() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_vpn%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsVpn()))));
    }

    // add `is_hosting` to the URL query string
    if (getIsHosting() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_hosting%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsHosting()))));
    }

    // add `is_relay` to the URL query string
    if (getIsRelay() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_relay%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsRelay()))));
    }

    // add `is_tor` to the URL query string
    if (getIsTor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_tor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsTor()))));
    }

    // add `is_cdn` to the URL query string
    if (getIsCdn() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_cdn%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsCdn()))));
    }

    // add `is_resproxy` to the URL query string
    if (getIsResproxy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_resproxy%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsResproxy()))));
    }

    // add `is_dcproxy` to the URL query string
    if (getIsDcproxy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_dcproxy%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsDcproxy()))));
    }

    // add `is_mobproxy` to the URL query string
    if (getIsMobproxy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_mobproxy%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsMobproxy()))));
    }

    // add `vpn` to the URL query string
    if (getVpn() != null) {
      joiner.add(getVpn().toUrlQueryString(prefix + "vpn" + suffix));
    }

    // add `hosting` to the URL query string
    if (getHosting() != null) {
      joiner.add(getHosting().toUrlQueryString(prefix + "hosting" + suffix));
    }

    // add `relay` to the URL query string
    if (getRelay() != null) {
      joiner.add(getRelay().toUrlQueryString(prefix + "relay" + suffix));
    }

    // add `tor` to the URL query string
    if (getTor() != null) {
      joiner.add(getTor().toUrlQueryString(prefix + "tor" + suffix));
    }

    // add `cdn` to the URL query string
    if (getCdn() != null) {
      joiner.add(getCdn().toUrlQueryString(prefix + "cdn" + suffix));
    }

    // add `resproxy` to the URL query string
    if (getResproxy() != null) {
      joiner.add(getResproxy().toUrlQueryString(prefix + "resproxy" + suffix));
    }

    // add `dcproxy` to the URL query string
    if (getDcproxy() != null) {
      joiner.add(getDcproxy().toUrlQueryString(prefix + "dcproxy" + suffix));
    }

    // add `mobproxy` to the URL query string
    if (getMobproxy() != null) {
      joiner.add(getMobproxy().toUrlQueryString(prefix + "mobproxy" + suffix));
    }

    return joiner.toString();
  }
}

