/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.09
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * The shared detail shape for the residential, datacenter and mobile proxy families, measured over a rolling 90 day window. Every key is present when the object is populated; the object is &#x60;{}&#x60; when its flag is false. 
 */
@JsonPropertyOrder({
  ProxyDetail.JSON_PROPERTY_PROVIDER,
  ProxyDetail.JSON_PROPERTY_FIRST_SEEN,
  ProxyDetail.JSON_PROPERTY_LAST_SEEN,
  ProxyDetail.JSON_PROPERTY_HITS,
  ProxyDetail.JSON_PROPERTY_HITS_DAYS_PCT,
  ProxyDetail.JSON_PROPERTY_PROVIDERS_NUM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ProxyDetail {
  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @javax.annotation.Nullable
  private String provider;

  public static final String JSON_PROPERTY_FIRST_SEEN = "first_seen";
  @javax.annotation.Nullable
  private LocalDate firstSeen;

  public static final String JSON_PROPERTY_LAST_SEEN = "last_seen";
  @javax.annotation.Nullable
  private LocalDate lastSeen;

  public static final String JSON_PROPERTY_HITS = "hits";
  @javax.annotation.Nullable
  private Integer hits;

  public static final String JSON_PROPERTY_HITS_DAYS_PCT = "hits_days_pct";
  @javax.annotation.Nullable
  private Integer hitsDaysPct;

  public static final String JSON_PROPERTY_PROVIDERS_NUM = "providers_num";
  @javax.annotation.Nullable
  private Integer providersNum;

  public ProxyDetail() { 
  }

  public ProxyDetail provider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * The proxy network, or an empty string where unattributed.
   * @return provider
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProvider() {
    return provider;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
  }


  public ProxyDetail firstSeen(@javax.annotation.Nullable LocalDate firstSeen) {
    this.firstSeen = firstSeen;
    return this;
  }

  /**
   * The earliest date within the window this address was seen in the pool.
   * @return firstSeen
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIRST_SEEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getFirstSeen() {
    return firstSeen;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRST_SEEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstSeen(@javax.annotation.Nullable LocalDate firstSeen) {
    this.firstSeen = firstSeen;
  }


  public ProxyDetail lastSeen(@javax.annotation.Nullable LocalDate lastSeen) {
    this.lastSeen = lastSeen;
    return this;
  }

  /**
   * The most recent date within the window this address was seen in the pool.
   * @return lastSeen
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_SEEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getLastSeen() {
    return lastSeen;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_SEEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastSeen(@javax.annotation.Nullable LocalDate lastSeen) {
    this.lastSeen = lastSeen;
  }


  public ProxyDetail hits(@javax.annotation.Nullable Integer hits) {
    this.hits = hits;
    return this;
  }

  /**
   * How many times the address was observed in the pool during the window.
   * @return hits
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HITS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getHits() {
    return hits;
  }


  @JsonProperty(value = JSON_PROPERTY_HITS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHits(@javax.annotation.Nullable Integer hits) {
    this.hits = hits;
  }


  public ProxyDetail hitsDaysPct(@javax.annotation.Nullable Integer hitsDaysPct) {
    this.hitsDaysPct = hitsDaysPct;
    return this;
  }

  /**
   * The share of days in the window on which the address was seen, as a percentage. A high value means a stable pool member rather than a one-off sighting. 
   * @return hitsDaysPct
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HITS_DAYS_PCT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getHitsDaysPct() {
    return hitsDaysPct;
  }


  @JsonProperty(value = JSON_PROPERTY_HITS_DAYS_PCT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHitsDaysPct(@javax.annotation.Nullable Integer hitsDaysPct) {
    this.hitsDaysPct = hitsDaysPct;
  }


  public ProxyDetail providersNum(@javax.annotation.Nullable Integer providersNum) {
    this.providersNum = providersNum;
    return this;
  }

  /**
   * How many distinct proxy networks this address was seen in.
   * @return providersNum
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROVIDERS_NUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getProvidersNum() {
    return providersNum;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDERS_NUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvidersNum(@javax.annotation.Nullable Integer providersNum) {
    this.providersNum = providersNum;
  }


  /**
   * Return true if this ProxyDetail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProxyDetail proxyDetail = (ProxyDetail) o;
    return Objects.equals(this.provider, proxyDetail.provider) &&
        Objects.equals(this.firstSeen, proxyDetail.firstSeen) &&
        Objects.equals(this.lastSeen, proxyDetail.lastSeen) &&
        Objects.equals(this.hits, proxyDetail.hits) &&
        Objects.equals(this.hitsDaysPct, proxyDetail.hitsDaysPct) &&
        Objects.equals(this.providersNum, proxyDetail.providersNum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provider, firstSeen, lastSeen, hits, hitsDaysPct, providersNum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProxyDetail {\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    firstSeen: ").append(toIndentedString(firstSeen)).append("\n");
    sb.append("    lastSeen: ").append(toIndentedString(lastSeen)).append("\n");
    sb.append("    hits: ").append(toIndentedString(hits)).append("\n");
    sb.append("    hitsDaysPct: ").append(toIndentedString(hitsDaysPct)).append("\n");
    sb.append("    providersNum: ").append(toIndentedString(providersNum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `provider` to the URL query string
    if (getProvider() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprovider%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProvider()))));
    }

    // add `first_seen` to the URL query string
    if (getFirstSeen() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfirst_seen%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFirstSeen()))));
    }

    // add `last_seen` to the URL query string
    if (getLastSeen() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slast_seen%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastSeen()))));
    }

    // add `hits` to the URL query string
    if (getHits() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shits%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHits()))));
    }

    // add `hits_days_pct` to the URL query string
    if (getHitsDaysPct() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shits_days_pct%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHitsDaysPct()))));
    }

    // add `providers_num` to the URL query string
    if (getProvidersNum() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproviders_num%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProvidersNum()))));
    }

    return joiner.toString();
  }
}

