/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.21
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * TokenResponse
 */
@JsonPropertyOrder({
  TokenResponse.JSON_PROPERTY_ACCESS_TOKEN,
  TokenResponse.JSON_PROPERTY_TOKEN_TYPE,
  TokenResponse.JSON_PROPERTY_EXPIRES_IN,
  TokenResponse.JSON_PROPERTY_REFRESH_TOKEN,
  TokenResponse.JSON_PROPERTY_SCOPE,
  TokenResponse.JSON_PROPERTY_APIKEY_ID,
  TokenResponse.JSON_PROPERTY_APIKEY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class TokenResponse {
  public static final String JSON_PROPERTY_ACCESS_TOKEN = "access_token";
  @javax.annotation.Nonnull
  private String accessToken;

  public static final String JSON_PROPERTY_TOKEN_TYPE = "token_type";
  @javax.annotation.Nonnull
  private String tokenType;

  public static final String JSON_PROPERTY_EXPIRES_IN = "expires_in";
  @javax.annotation.Nonnull
  private Integer expiresIn;

  public static final String JSON_PROPERTY_REFRESH_TOKEN = "refresh_token";
  @javax.annotation.Nullable
  private String refreshToken;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @javax.annotation.Nullable
  private String scope;

  public static final String JSON_PROPERTY_APIKEY_ID = "mslm:apikey_id";
  @javax.annotation.Nullable
  private String apikeyId;

  public static final String JSON_PROPERTY_APIKEY = "mslm:apikey";
  @javax.annotation.Nullable
  private String apikey;

  public TokenResponse() { 
  }

  public TokenResponse accessToken(@javax.annotation.Nonnull String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

  /**
   * Get accessToken
   * @return accessToken
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACCESS_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccessToken() {
    return accessToken;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCESS_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccessToken(@javax.annotation.Nonnull String accessToken) {
    this.accessToken = accessToken;
  }


  public TokenResponse tokenType(@javax.annotation.Nonnull String tokenType) {
    this.tokenType = tokenType;
    return this;
  }

  /**
   * Always &#x60;Bearer&#x60;.
   * @return tokenType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOKEN_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTokenType() {
    return tokenType;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKEN_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTokenType(@javax.annotation.Nonnull String tokenType) {
    this.tokenType = tokenType;
  }


  public TokenResponse expiresIn(@javax.annotation.Nonnull Integer expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

  /**
   * Seconds until the access token expires.
   * @return expiresIn
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_IN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getExpiresIn() {
    return expiresIn;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_IN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiresIn(@javax.annotation.Nonnull Integer expiresIn) {
    this.expiresIn = expiresIn;
  }


  public TokenResponse refreshToken(@javax.annotation.Nullable String refreshToken) {
    this.refreshToken = refreshToken;
    return this;
  }

  /**
   * Always returned. A refresh consumes the token it presents, so keep this one.
   * @return refreshToken
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REFRESH_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRefreshToken() {
    return refreshToken;
  }


  @JsonProperty(value = JSON_PROPERTY_REFRESH_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefreshToken(@javax.annotation.Nullable String refreshToken) {
    this.refreshToken = refreshToken;
  }


  public TokenResponse scope(@javax.annotation.Nullable String scope) {
    this.scope = scope;
    return this;
  }

  /**
   * What was actually granted, which may be narrower than what was asked for.
   * @return scope
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getScope() {
    return scope;
  }


  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(@javax.annotation.Nullable String scope) {
    this.scope = scope;
  }


  public TokenResponse apikeyId(@javax.annotation.Nullable String apikeyId) {
    this.apikeyId = apikeyId;
    return this;
  }

  /**
   * Not part of OAuth. The ID of the API key the person picked when they approved, returned by every grant while this authorization may still read that key back. Absent when no key was picked, or when the person&#39;s role no longer allows reading keys back. 
   * @return apikeyId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APIKEY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getApikeyId() {
    return apikeyId;
  }


  @JsonProperty(value = JSON_PROPERTY_APIKEY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApikeyId(@javax.annotation.Nullable String apikeyId) {
    this.apikeyId = apikeyId;
  }


  public TokenResponse apikey(@javax.annotation.Nullable String apikey) {
    this.apikey = apikey;
    return this;
  }

  /**
   * Not part of OAuth. The API key itself, so a device ends up holding an ordinary key. Returned by the device code and authorization code grants only, never by a refresh, and only alongside &#x60;mslm:apikey_id&#x60;. Absent when that key&#39;s secret cannot be read back, which is the case for a key created before keys could be shown again in the console; a rotated key can be. 
   * @return apikey
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APIKEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getApikey() {
    return apikey;
  }


  @JsonProperty(value = JSON_PROPERTY_APIKEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApikey(@javax.annotation.Nullable String apikey) {
    this.apikey = apikey;
  }


  /**
   * Return true if this TokenResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenResponse tokenResponse = (TokenResponse) o;
    return Objects.equals(this.accessToken, tokenResponse.accessToken) &&
        Objects.equals(this.tokenType, tokenResponse.tokenType) &&
        Objects.equals(this.expiresIn, tokenResponse.expiresIn) &&
        Objects.equals(this.refreshToken, tokenResponse.refreshToken) &&
        Objects.equals(this.scope, tokenResponse.scope) &&
        Objects.equals(this.apikeyId, tokenResponse.apikeyId) &&
        Objects.equals(this.apikey, tokenResponse.apikey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, tokenType, expiresIn, refreshToken, scope, apikeyId, apikey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenResponse {\n");
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    tokenType: ").append(toIndentedString(tokenType)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    refreshToken: ").append(toIndentedString(refreshToken)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    apikeyId: ").append(toIndentedString(apikeyId)).append("\n");
    sb.append("    apikey: ").append(toIndentedString(apikey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `access_token` to the URL query string
    if (getAccessToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saccess_token%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccessToken()))));
    }

    // add `token_type` to the URL query string
    if (getTokenType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stoken_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenType()))));
    }

    // add `expires_in` to the URL query string
    if (getExpiresIn() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpires_in%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiresIn()))));
    }

    // add `refresh_token` to the URL query string
    if (getRefreshToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srefresh_token%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRefreshToken()))));
    }

    // add `scope` to the URL query string
    if (getScope() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sscope%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getScope()))));
    }

    // add `mslm:apikey_id` to the URL query string
    if (getApikeyId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smslm:apikey_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getApikeyId()))));
    }

    // add `mslm:apikey` to the URL query string
    if (getApikey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smslm:apikey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getApikey()))));
    }

    return joiner.toString();
  }
}

