/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.03
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.vpndetection.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.vpndetection.internal.ApiClient;
/**
 * What is known about the VPN attribution. Every key is present when the object is populated, empty values included; the object is &#x60;{}&#x60; when &#x60;is_vpn&#x60; is false. &#x60;confidence&#x60; and &#x60;method&#x60; are max only, so on a lower plan they are absent from a populated object rather than empty. 
 */
@JsonPropertyOrder({
  VpnDetail.JSON_PROPERTY_PROVIDER,
  VpnDetail.JSON_PROPERTY_LAST_SEEN,
  VpnDetail.JSON_PROPERTY_CONFIDENCE,
  VpnDetail.JSON_PROPERTY_METHOD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class VpnDetail {
  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @javax.annotation.Nullable
  private String provider;

  public static final String JSON_PROPERTY_LAST_SEEN = "last_seen";
  @javax.annotation.Nullable
  private LocalDate lastSeen;

  public static final String JSON_PROPERTY_CONFIDENCE = "confidence";
  @javax.annotation.Nullable
  private String confidence;

  public static final String JSON_PROPERTY_METHOD = "method";
  @javax.annotation.Nullable
  private String method;

  public VpnDetail() { 
  }

  public VpnDetail provider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * The VPN provider, or an empty string for an unattributed range.
   * @return provider
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProvider() {
    return provider;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
  }


  public VpnDetail lastSeen(@javax.annotation.Nullable LocalDate lastSeen) {
    this.lastSeen = lastSeen;
    return this;
  }

  /**
   * The most recent date this address was observed as VPN infrastructure.
   * @return lastSeen
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_SEEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getLastSeen() {
    return lastSeen;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_SEEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastSeen(@javax.annotation.Nullable LocalDate lastSeen) {
    this.lastSeen = lastSeen;
  }


  public VpnDetail confidence(@javax.annotation.Nullable String confidence) {
    this.confidence = confidence;
    return this;
  }

  /**
   * How strongly the attribution is supported. Max only.
   * @return confidence
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getConfidence() {
    return confidence;
  }


  @JsonProperty(value = JSON_PROPERTY_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfidence(@javax.annotation.Nullable String confidence) {
    this.confidence = confidence;
  }


  public VpnDetail method(@javax.annotation.Nullable String method) {
    this.method = method;
    return this;
  }

  /**
   * How the address was attributed to the provider. Max only.
   * @return method
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMethod() {
    return method;
  }


  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethod(@javax.annotation.Nullable String method) {
    this.method = method;
  }


  /**
   * Return true if this VpnDetail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VpnDetail vpnDetail = (VpnDetail) o;
    return Objects.equals(this.provider, vpnDetail.provider) &&
        Objects.equals(this.lastSeen, vpnDetail.lastSeen) &&
        Objects.equals(this.confidence, vpnDetail.confidence) &&
        Objects.equals(this.method, vpnDetail.method);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provider, lastSeen, confidence, method);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VpnDetail {\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    lastSeen: ").append(toIndentedString(lastSeen)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `provider` to the URL query string
    if (getProvider() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprovider%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProvider()))));
    }

    // add `last_seen` to the URL query string
    if (getLastSeen() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slast_seen%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastSeen()))));
    }

    // add `confidence` to the URL query string
    if (getConfidence() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sconfidence%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConfidence()))));
    }

    // add `method` to the URL query string
    if (getMethod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMethod()))));
    }

    return joiner.toString();
  }
}

