/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.18
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vpndetection.api;

import io.vpndetection.internal.ApiClient;
import io.vpndetection.internal.ApiException;
import io.vpndetection.internal.ApiResponse;
import io.vpndetection.internal.Configuration;
import io.vpndetection.internal.Pair;

import io.vpndetection.model.AccountCreateApikeyRequest;
import io.vpndetection.model.AccountCreatedApikey;
import io.vpndetection.model.AccountRc;
import io.vpndetection.model.AccountRevealedApikey;
import io.vpndetection.model.ApikeyList;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ApiKeysWireApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public ApiKeysWireApi() {
    this(Configuration.getDefaultApiClient());
  }

  public ApiKeysWireApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create
   * Creates a key and returns its secret.  This is the ONLY response that ever carries the secret, and only because this is the moment it comes into existence. Store it now. 
   * @param accountCreateApikeyRequest  (required)
   * @return AccountCreatedApikey
   * @throws ApiException if fails to make API call
   */
  public AccountCreatedApikey accountCreateApikey(@javax.annotation.Nonnull AccountCreateApikeyRequest accountCreateApikeyRequest) throws ApiException {
    return accountCreateApikey(accountCreateApikeyRequest, null);
  }

  /**
   * Create
   * Creates a key and returns its secret.  This is the ONLY response that ever carries the secret, and only because this is the moment it comes into existence. Store it now. 
   * @param accountCreateApikeyRequest  (required)
   * @param headers Optional headers to include in the request
   * @return AccountCreatedApikey
   * @throws ApiException if fails to make API call
   */
  public AccountCreatedApikey accountCreateApikey(@javax.annotation.Nonnull AccountCreateApikeyRequest accountCreateApikeyRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<AccountCreatedApikey> localVarResponse = accountCreateApikeyWithHttpInfo(accountCreateApikeyRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Create
   * Creates a key and returns its secret.  This is the ONLY response that ever carries the secret, and only because this is the moment it comes into existence. Store it now. 
   * @param accountCreateApikeyRequest  (required)
   * @return ApiResponse&lt;AccountCreatedApikey&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AccountCreatedApikey> accountCreateApikeyWithHttpInfo(@javax.annotation.Nonnull AccountCreateApikeyRequest accountCreateApikeyRequest) throws ApiException {
    return accountCreateApikeyWithHttpInfo(accountCreateApikeyRequest, null);
  }

  /**
   * Create
   * Creates a key and returns its secret.  This is the ONLY response that ever carries the secret, and only because this is the moment it comes into existence. Store it now. 
   * @param accountCreateApikeyRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;AccountCreatedApikey&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AccountCreatedApikey> accountCreateApikeyWithHttpInfo(@javax.annotation.Nonnull AccountCreateApikeyRequest accountCreateApikeyRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = accountCreateApikeyRequestBuilder(accountCreateApikeyRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("accountCreateApikey", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<AccountCreatedApikey>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        AccountCreatedApikey responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<AccountCreatedApikey>() {});
        

        return new ApiResponse<AccountCreatedApikey>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder accountCreateApikeyRequestBuilder(@javax.annotation.Nonnull AccountCreateApikeyRequest accountCreateApikeyRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'accountCreateApikeyRequest' is set
    if (accountCreateApikeyRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'accountCreateApikeyRequest' when calling accountCreateApikey");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/iam/apikeys";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(accountCreateApikeyRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List
   * Metadata only. A key&#39;s secret is never in a list - not here and not in the console - because a list is the response that ends up in logs, caches and support tickets.  &#x60;retrievable&#x60; says whether the secret could still be read back at all. A key issued before this product stored secrets recoverably was never kept, so &#x60;reveal&#x60; will refuse it permanently; rotating produces one that can be read. 
   * @return ApikeyList
   * @throws ApiException if fails to make API call
   */
  public ApikeyList accountListApikeys() throws ApiException {
    return accountListApikeys(null);
  }

  /**
   * List
   * Metadata only. A key&#39;s secret is never in a list - not here and not in the console - because a list is the response that ends up in logs, caches and support tickets.  &#x60;retrievable&#x60; says whether the secret could still be read back at all. A key issued before this product stored secrets recoverably was never kept, so &#x60;reveal&#x60; will refuse it permanently; rotating produces one that can be read. 
   * @param headers Optional headers to include in the request
   * @return ApikeyList
   * @throws ApiException if fails to make API call
   */
  public ApikeyList accountListApikeys(Map<String, String> headers) throws ApiException {
    ApiResponse<ApikeyList> localVarResponse = accountListApikeysWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * List
   * Metadata only. A key&#39;s secret is never in a list - not here and not in the console - because a list is the response that ends up in logs, caches and support tickets.  &#x60;retrievable&#x60; says whether the secret could still be read back at all. A key issued before this product stored secrets recoverably was never kept, so &#x60;reveal&#x60; will refuse it permanently; rotating produces one that can be read. 
   * @return ApiResponse&lt;ApikeyList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ApikeyList> accountListApikeysWithHttpInfo() throws ApiException {
    return accountListApikeysWithHttpInfo(null);
  }

  /**
   * List
   * Metadata only. A key&#39;s secret is never in a list - not here and not in the console - because a list is the response that ends up in logs, caches and support tickets.  &#x60;retrievable&#x60; says whether the secret could still be read back at all. A key issued before this product stored secrets recoverably was never kept, so &#x60;reveal&#x60; will refuse it permanently; rotating produces one that can be read. 
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ApikeyList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ApikeyList> accountListApikeysWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = accountListApikeysRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("accountListApikeys", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ApikeyList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ApikeyList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ApikeyList>() {});
        

        return new ApiResponse<ApikeyList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder accountListApikeysRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/iam/apikeys";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Reveal
   * Returns an existing key&#39;s secret.  Its own scope rather than part of &#x60;apikeys.manage&#x60;, because the two are different acts: rotating replaces a secret you never see, while this hands one over.  Refused with &#x60;NOT_RETRIEVABLE&#x60; for a key issued before this product stored secrets recoverably - that secret was never kept, so no retry will ever produce it. Rotate the key instead. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @return AccountRevealedApikey
   * @throws ApiException if fails to make API call
   */
  public AccountRevealedApikey accountRevealApikey(@javax.annotation.Nonnull UUID id) throws ApiException {
    return accountRevealApikey(id, null);
  }

  /**
   * Reveal
   * Returns an existing key&#39;s secret.  Its own scope rather than part of &#x60;apikeys.manage&#x60;, because the two are different acts: rotating replaces a secret you never see, while this hands one over.  Refused with &#x60;NOT_RETRIEVABLE&#x60; for a key issued before this product stored secrets recoverably - that secret was never kept, so no retry will ever produce it. Rotate the key instead. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @param headers Optional headers to include in the request
   * @return AccountRevealedApikey
   * @throws ApiException if fails to make API call
   */
  public AccountRevealedApikey accountRevealApikey(@javax.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    ApiResponse<AccountRevealedApikey> localVarResponse = accountRevealApikeyWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Reveal
   * Returns an existing key&#39;s secret.  Its own scope rather than part of &#x60;apikeys.manage&#x60;, because the two are different acts: rotating replaces a secret you never see, while this hands one over.  Refused with &#x60;NOT_RETRIEVABLE&#x60; for a key issued before this product stored secrets recoverably - that secret was never kept, so no retry will ever produce it. Rotate the key instead. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @return ApiResponse&lt;AccountRevealedApikey&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AccountRevealedApikey> accountRevealApikeyWithHttpInfo(@javax.annotation.Nonnull UUID id) throws ApiException {
    return accountRevealApikeyWithHttpInfo(id, null);
  }

  /**
   * Reveal
   * Returns an existing key&#39;s secret.  Its own scope rather than part of &#x60;apikeys.manage&#x60;, because the two are different acts: rotating replaces a secret you never see, while this hands one over.  Refused with &#x60;NOT_RETRIEVABLE&#x60; for a key issued before this product stored secrets recoverably - that secret was never kept, so no retry will ever produce it. Rotate the key instead. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;AccountRevealedApikey&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AccountRevealedApikey> accountRevealApikeyWithHttpInfo(@javax.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = accountRevealApikeyRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("accountRevealApikey", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<AccountRevealedApikey>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        AccountRevealedApikey responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<AccountRevealedApikey>() {});
        

        return new ApiResponse<AccountRevealedApikey>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder accountRevealApikeyRequestBuilder(@javax.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling accountRevealApikey");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/iam/apikeys/{id}/reveal"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Revoke
   * Stops the key working. Revocation is soft: the key stays listed with a &#x60;revoked_at&#x60;, because the organization still owns whatever it did while it was alive. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @return AccountRc
   * @throws ApiException if fails to make API call
   */
  public AccountRc accountRevokeApikey(@javax.annotation.Nonnull UUID id) throws ApiException {
    return accountRevokeApikey(id, null);
  }

  /**
   * Revoke
   * Stops the key working. Revocation is soft: the key stays listed with a &#x60;revoked_at&#x60;, because the organization still owns whatever it did while it was alive. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @param headers Optional headers to include in the request
   * @return AccountRc
   * @throws ApiException if fails to make API call
   */
  public AccountRc accountRevokeApikey(@javax.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    ApiResponse<AccountRc> localVarResponse = accountRevokeApikeyWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Revoke
   * Stops the key working. Revocation is soft: the key stays listed with a &#x60;revoked_at&#x60;, because the organization still owns whatever it did while it was alive. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @return ApiResponse&lt;AccountRc&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AccountRc> accountRevokeApikeyWithHttpInfo(@javax.annotation.Nonnull UUID id) throws ApiException {
    return accountRevokeApikeyWithHttpInfo(id, null);
  }

  /**
   * Revoke
   * Stops the key working. Revocation is soft: the key stays listed with a &#x60;revoked_at&#x60;, because the organization still owns whatever it did while it was alive. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;AccountRc&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AccountRc> accountRevokeApikeyWithHttpInfo(@javax.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = accountRevokeApikeyRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("accountRevokeApikey", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<AccountRc>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        AccountRc responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<AccountRc>() {});
        

        return new ApiResponse<AccountRc>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder accountRevokeApikeyRequestBuilder(@javax.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling accountRevokeApikey");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/iam/apikeys/{id}/revoke"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Rotate
   * Replaces the secret behind a key, keeping its id, name and settings. The previous secret stops working immediately. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @return AccountCreatedApikey
   * @throws ApiException if fails to make API call
   */
  public AccountCreatedApikey accountRotateApikey(@javax.annotation.Nonnull UUID id) throws ApiException {
    return accountRotateApikey(id, null);
  }

  /**
   * Rotate
   * Replaces the secret behind a key, keeping its id, name and settings. The previous secret stops working immediately. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @param headers Optional headers to include in the request
   * @return AccountCreatedApikey
   * @throws ApiException if fails to make API call
   */
  public AccountCreatedApikey accountRotateApikey(@javax.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    ApiResponse<AccountCreatedApikey> localVarResponse = accountRotateApikeyWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Rotate
   * Replaces the secret behind a key, keeping its id, name and settings. The previous secret stops working immediately. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @return ApiResponse&lt;AccountCreatedApikey&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AccountCreatedApikey> accountRotateApikeyWithHttpInfo(@javax.annotation.Nonnull UUID id) throws ApiException {
    return accountRotateApikeyWithHttpInfo(id, null);
  }

  /**
   * Rotate
   * Replaces the secret behind a key, keeping its id, name and settings. The previous secret stops working immediately. 
   * @param id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;AccountCreatedApikey&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AccountCreatedApikey> accountRotateApikeyWithHttpInfo(@javax.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = accountRotateApikeyRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("accountRotateApikey", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<AccountCreatedApikey>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        AccountCreatedApikey responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<AccountCreatedApikey>() {});
        

        return new ApiResponse<AccountCreatedApikey>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder accountRotateApikeyRequestBuilder(@javax.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling accountRotateApikey");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/iam/apikeys/{id}/rotate"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
