/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.15
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vpndetection.api;

import io.vpndetection.internal.ApiClient;
import io.vpndetection.internal.ApiException;
import io.vpndetection.internal.ApiResponse;
import io.vpndetection.internal.Configuration;
import io.vpndetection.internal.Pair;

import io.vpndetection.model.DeviceAuthorization;
import io.vpndetection.model.OauthError;
import io.vpndetection.model.OauthMetadata;
import io.vpndetection.model.TokenResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AuthorizationWireApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public AuthorizationWireApi() {
    this(Configuration.getDefaultApiClient());
  }

  public AuthorizationWireApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Authorize
   * The browser entry point for the authorization-code flow. This is a redirect target, not something to call from code.  An unknown &#x60;client_id&#x60; or an unregistered &#x60;redirect_uri&#x60; is shown to the USER and never redirected, because sending an error to an address we have not verified belongs to you is how an open redirector works. Everything else comes back to your &#x60;redirect_uri&#x60; with &#x60;error&#x60;, your &#x60;state&#x60;, and &#x60;iss&#x60;. 
   * @param clientId  (required)
   * @param redirectUri  (required)
   * @param responseType  (required)
   * @param codeChallenge  (required)
   * @param codeChallengeMethod S256 only. &#x60;plain&#x60; is refused rather than downgraded. (optional)
   * @param scope  (optional)
   * @param state Returned unchanged. Use it to bind the response to your request. (optional)
   * @param resource RFC 8707. What the token is FOR, so it cannot be replayed elsewhere. (optional)
   * @throws ApiException if fails to make API call
   */
  public void oauthAuthorize(@javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String redirectUri, @javax.annotation.Nonnull String responseType, @javax.annotation.Nonnull String codeChallenge, @javax.annotation.Nullable String codeChallengeMethod, @javax.annotation.Nullable String scope, @javax.annotation.Nullable String state, @javax.annotation.Nullable String resource) throws ApiException {
    oauthAuthorize(clientId, redirectUri, responseType, codeChallenge, codeChallengeMethod, scope, state, resource, null);
  }

  /**
   * Authorize
   * The browser entry point for the authorization-code flow. This is a redirect target, not something to call from code.  An unknown &#x60;client_id&#x60; or an unregistered &#x60;redirect_uri&#x60; is shown to the USER and never redirected, because sending an error to an address we have not verified belongs to you is how an open redirector works. Everything else comes back to your &#x60;redirect_uri&#x60; with &#x60;error&#x60;, your &#x60;state&#x60;, and &#x60;iss&#x60;. 
   * @param clientId  (required)
   * @param redirectUri  (required)
   * @param responseType  (required)
   * @param codeChallenge  (required)
   * @param codeChallengeMethod S256 only. &#x60;plain&#x60; is refused rather than downgraded. (optional)
   * @param scope  (optional)
   * @param state Returned unchanged. Use it to bind the response to your request. (optional)
   * @param resource RFC 8707. What the token is FOR, so it cannot be replayed elsewhere. (optional)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void oauthAuthorize(@javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String redirectUri, @javax.annotation.Nonnull String responseType, @javax.annotation.Nonnull String codeChallenge, @javax.annotation.Nullable String codeChallengeMethod, @javax.annotation.Nullable String scope, @javax.annotation.Nullable String state, @javax.annotation.Nullable String resource, Map<String, String> headers) throws ApiException {
    oauthAuthorizeWithHttpInfo(clientId, redirectUri, responseType, codeChallenge, codeChallengeMethod, scope, state, resource, headers);
  }

  /**
   * Authorize
   * The browser entry point for the authorization-code flow. This is a redirect target, not something to call from code.  An unknown &#x60;client_id&#x60; or an unregistered &#x60;redirect_uri&#x60; is shown to the USER and never redirected, because sending an error to an address we have not verified belongs to you is how an open redirector works. Everything else comes back to your &#x60;redirect_uri&#x60; with &#x60;error&#x60;, your &#x60;state&#x60;, and &#x60;iss&#x60;. 
   * @param clientId  (required)
   * @param redirectUri  (required)
   * @param responseType  (required)
   * @param codeChallenge  (required)
   * @param codeChallengeMethod S256 only. &#x60;plain&#x60; is refused rather than downgraded. (optional)
   * @param scope  (optional)
   * @param state Returned unchanged. Use it to bind the response to your request. (optional)
   * @param resource RFC 8707. What the token is FOR, so it cannot be replayed elsewhere. (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> oauthAuthorizeWithHttpInfo(@javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String redirectUri, @javax.annotation.Nonnull String responseType, @javax.annotation.Nonnull String codeChallenge, @javax.annotation.Nullable String codeChallengeMethod, @javax.annotation.Nullable String scope, @javax.annotation.Nullable String state, @javax.annotation.Nullable String resource) throws ApiException {
    return oauthAuthorizeWithHttpInfo(clientId, redirectUri, responseType, codeChallenge, codeChallengeMethod, scope, state, resource, null);
  }

  /**
   * Authorize
   * The browser entry point for the authorization-code flow. This is a redirect target, not something to call from code.  An unknown &#x60;client_id&#x60; or an unregistered &#x60;redirect_uri&#x60; is shown to the USER and never redirected, because sending an error to an address we have not verified belongs to you is how an open redirector works. Everything else comes back to your &#x60;redirect_uri&#x60; with &#x60;error&#x60;, your &#x60;state&#x60;, and &#x60;iss&#x60;. 
   * @param clientId  (required)
   * @param redirectUri  (required)
   * @param responseType  (required)
   * @param codeChallenge  (required)
   * @param codeChallengeMethod S256 only. &#x60;plain&#x60; is refused rather than downgraded. (optional)
   * @param scope  (optional)
   * @param state Returned unchanged. Use it to bind the response to your request. (optional)
   * @param resource RFC 8707. What the token is FOR, so it cannot be replayed elsewhere. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> oauthAuthorizeWithHttpInfo(@javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String redirectUri, @javax.annotation.Nonnull String responseType, @javax.annotation.Nonnull String codeChallenge, @javax.annotation.Nullable String codeChallengeMethod, @javax.annotation.Nullable String scope, @javax.annotation.Nullable String state, @javax.annotation.Nullable String resource, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = oauthAuthorizeRequestBuilder(clientId, redirectUri, responseType, codeChallenge, codeChallengeMethod, scope, state, resource, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("oauthAuthorize", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder oauthAuthorizeRequestBuilder(@javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String redirectUri, @javax.annotation.Nonnull String responseType, @javax.annotation.Nonnull String codeChallenge, @javax.annotation.Nullable String codeChallengeMethod, @javax.annotation.Nullable String scope, @javax.annotation.Nullable String state, @javax.annotation.Nullable String resource, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'clientId' is set
    if (clientId == null) {
      throw new ApiException(400, "Missing the required parameter 'clientId' when calling oauthAuthorize");
    }
    // verify the required parameter 'redirectUri' is set
    if (redirectUri == null) {
      throw new ApiException(400, "Missing the required parameter 'redirectUri' when calling oauthAuthorize");
    }
    // verify the required parameter 'responseType' is set
    if (responseType == null) {
      throw new ApiException(400, "Missing the required parameter 'responseType' when calling oauthAuthorize");
    }
    // verify the required parameter 'codeChallenge' is set
    if (codeChallenge == null) {
      throw new ApiException(400, "Missing the required parameter 'codeChallenge' when calling oauthAuthorize");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/oauth/authorize";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "client_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("client_id", clientId));
    localVarQueryParameterBaseName = "redirect_uri";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("redirect_uri", redirectUri));
    localVarQueryParameterBaseName = "response_type";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("response_type", responseType));
    localVarQueryParameterBaseName = "code_challenge";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("code_challenge", codeChallenge));
    localVarQueryParameterBaseName = "code_challenge_method";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("code_challenge_method", codeChallengeMethod));
    localVarQueryParameterBaseName = "scope";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("scope", scope));
    localVarQueryParameterBaseName = "state";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("state", state));
    localVarQueryParameterBaseName = "resource";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("resource", resource));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Device authorization
   * Starts the device flow. Show the &#x60;user_code&#x60; to the person and send them to &#x60;verification_uri&#x60;; &#x60;verification_uri_complete&#x60; has the code already embedded, which is what to open if you can open a browser at all.  Then poll &#x60;/oauth/token&#x60;, no faster than &#x60;interval&#x60; seconds. 
   * @param clientId  (required)
   * @param scope Space-delimited. Anything your client is not registered for is dropped rather than refused. (optional)
   * @param resource RFC 8707: what the token is for. (optional)
   * @return DeviceAuthorization
   * @throws ApiException if fails to make API call
   */
  public DeviceAuthorization oauthDeviceAuthorization(@javax.annotation.Nonnull String clientId, @javax.annotation.Nullable String scope, @javax.annotation.Nullable String resource) throws ApiException {
    return oauthDeviceAuthorization(clientId, scope, resource, null);
  }

  /**
   * Device authorization
   * Starts the device flow. Show the &#x60;user_code&#x60; to the person and send them to &#x60;verification_uri&#x60;; &#x60;verification_uri_complete&#x60; has the code already embedded, which is what to open if you can open a browser at all.  Then poll &#x60;/oauth/token&#x60;, no faster than &#x60;interval&#x60; seconds. 
   * @param clientId  (required)
   * @param scope Space-delimited. Anything your client is not registered for is dropped rather than refused. (optional)
   * @param resource RFC 8707: what the token is for. (optional)
   * @param headers Optional headers to include in the request
   * @return DeviceAuthorization
   * @throws ApiException if fails to make API call
   */
  public DeviceAuthorization oauthDeviceAuthorization(@javax.annotation.Nonnull String clientId, @javax.annotation.Nullable String scope, @javax.annotation.Nullable String resource, Map<String, String> headers) throws ApiException {
    ApiResponse<DeviceAuthorization> localVarResponse = oauthDeviceAuthorizationWithHttpInfo(clientId, scope, resource, headers);
    return localVarResponse.getData();
  }

  /**
   * Device authorization
   * Starts the device flow. Show the &#x60;user_code&#x60; to the person and send them to &#x60;verification_uri&#x60;; &#x60;verification_uri_complete&#x60; has the code already embedded, which is what to open if you can open a browser at all.  Then poll &#x60;/oauth/token&#x60;, no faster than &#x60;interval&#x60; seconds. 
   * @param clientId  (required)
   * @param scope Space-delimited. Anything your client is not registered for is dropped rather than refused. (optional)
   * @param resource RFC 8707: what the token is for. (optional)
   * @return ApiResponse&lt;DeviceAuthorization&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeviceAuthorization> oauthDeviceAuthorizationWithHttpInfo(@javax.annotation.Nonnull String clientId, @javax.annotation.Nullable String scope, @javax.annotation.Nullable String resource) throws ApiException {
    return oauthDeviceAuthorizationWithHttpInfo(clientId, scope, resource, null);
  }

  /**
   * Device authorization
   * Starts the device flow. Show the &#x60;user_code&#x60; to the person and send them to &#x60;verification_uri&#x60;; &#x60;verification_uri_complete&#x60; has the code already embedded, which is what to open if you can open a browser at all.  Then poll &#x60;/oauth/token&#x60;, no faster than &#x60;interval&#x60; seconds. 
   * @param clientId  (required)
   * @param scope Space-delimited. Anything your client is not registered for is dropped rather than refused. (optional)
   * @param resource RFC 8707: what the token is for. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DeviceAuthorization&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeviceAuthorization> oauthDeviceAuthorizationWithHttpInfo(@javax.annotation.Nonnull String clientId, @javax.annotation.Nullable String scope, @javax.annotation.Nullable String resource, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = oauthDeviceAuthorizationRequestBuilder(clientId, scope, resource, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("oauthDeviceAuthorization", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DeviceAuthorization>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DeviceAuthorization responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DeviceAuthorization>() {});
        

        return new ApiResponse<DeviceAuthorization>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder oauthDeviceAuthorizationRequestBuilder(@javax.annotation.Nonnull String clientId, @javax.annotation.Nullable String scope, @javax.annotation.Nullable String resource, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'clientId' is set
    if (clientId == null) {
      throw new ApiException(400, "Missing the required parameter 'clientId' when calling oauthDeviceAuthorization");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/oauth/device_authorization";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    List<NameValuePair> formValues = new ArrayList<>();
    if (clientId != null) {
        formValues.add(new BasicNameValuePair("client_id", clientId.toString()));
    }
    if (scope != null) {
        formValues.add(new BasicNameValuePair("scope", scope.toString()));
    }
    if (resource != null) {
        formValues.add(new BasicNameValuePair("resource", resource.toString()));
    }
    HttpEntity entity = new UrlEncodedFormEntity(formValues, java.nio.charset.StandardCharsets.UTF_8);
    ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
    try {
        entity.writeTo(formOutputStream);
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
    byte[] formBytes = formOutputStream.toByteArray();
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formBytes)));
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Discovery
   * RFC 8414 authorization server metadata: the endpoints, the grant types and the scopes this server supports.  Read this rather than hardcoding endpoints. It is also served at &#x60;/.well-known/openid-configuration&#x60;, identically, because several clients probe that path first. 
   * @return OauthMetadata
   * @throws ApiException if fails to make API call
   */
  public OauthMetadata oauthMetadata() throws ApiException {
    return oauthMetadata(null);
  }

  /**
   * Discovery
   * RFC 8414 authorization server metadata: the endpoints, the grant types and the scopes this server supports.  Read this rather than hardcoding endpoints. It is also served at &#x60;/.well-known/openid-configuration&#x60;, identically, because several clients probe that path first. 
   * @param headers Optional headers to include in the request
   * @return OauthMetadata
   * @throws ApiException if fails to make API call
   */
  public OauthMetadata oauthMetadata(Map<String, String> headers) throws ApiException {
    ApiResponse<OauthMetadata> localVarResponse = oauthMetadataWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Discovery
   * RFC 8414 authorization server metadata: the endpoints, the grant types and the scopes this server supports.  Read this rather than hardcoding endpoints. It is also served at &#x60;/.well-known/openid-configuration&#x60;, identically, because several clients probe that path first. 
   * @return ApiResponse&lt;OauthMetadata&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<OauthMetadata> oauthMetadataWithHttpInfo() throws ApiException {
    return oauthMetadataWithHttpInfo(null);
  }

  /**
   * Discovery
   * RFC 8414 authorization server metadata: the endpoints, the grant types and the scopes this server supports.  Read this rather than hardcoding endpoints. It is also served at &#x60;/.well-known/openid-configuration&#x60;, identically, because several clients probe that path first. 
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;OauthMetadata&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<OauthMetadata> oauthMetadataWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = oauthMetadataRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("oauthMetadata", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<OauthMetadata>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        OauthMetadata responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<OauthMetadata>() {});
        

        return new ApiResponse<OauthMetadata>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder oauthMetadataRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/.well-known/oauth-authorization-server";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Revoke
   * RFC 7009. Always answers 200, including for a token that was never valid - an endpoint that distinguished the two would be a way to test whether a stolen string is a live credential.  Revoking a REFRESH token ends the whole authorization and takes its access tokens with it. Revoking an access token affects only that token. 
   * @param token  (required)
   * @param clientId  (optional)
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object oauthRevoke(@javax.annotation.Nonnull String token, @javax.annotation.Nullable String clientId) throws ApiException {
    return oauthRevoke(token, clientId, null);
  }

  /**
   * Revoke
   * RFC 7009. Always answers 200, including for a token that was never valid - an endpoint that distinguished the two would be a way to test whether a stolen string is a live credential.  Revoking a REFRESH token ends the whole authorization and takes its access tokens with it. Revoking an access token affects only that token. 
   * @param token  (required)
   * @param clientId  (optional)
   * @param headers Optional headers to include in the request
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object oauthRevoke(@javax.annotation.Nonnull String token, @javax.annotation.Nullable String clientId, Map<String, String> headers) throws ApiException {
    ApiResponse<Object> localVarResponse = oauthRevokeWithHttpInfo(token, clientId, headers);
    return localVarResponse.getData();
  }

  /**
   * Revoke
   * RFC 7009. Always answers 200, including for a token that was never valid - an endpoint that distinguished the two would be a way to test whether a stolen string is a live credential.  Revoking a REFRESH token ends the whole authorization and takes its access tokens with it. Revoking an access token affects only that token. 
   * @param token  (required)
   * @param clientId  (optional)
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> oauthRevokeWithHttpInfo(@javax.annotation.Nonnull String token, @javax.annotation.Nullable String clientId) throws ApiException {
    return oauthRevokeWithHttpInfo(token, clientId, null);
  }

  /**
   * Revoke
   * RFC 7009. Always answers 200, including for a token that was never valid - an endpoint that distinguished the two would be a way to test whether a stolen string is a live credential.  Revoking a REFRESH token ends the whole authorization and takes its access tokens with it. Revoking an access token affects only that token. 
   * @param token  (required)
   * @param clientId  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> oauthRevokeWithHttpInfo(@javax.annotation.Nonnull String token, @javax.annotation.Nullable String clientId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = oauthRevokeRequestBuilder(token, clientId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("oauthRevoke", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Object>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Object responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Object>() {});
        

        return new ApiResponse<Object>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder oauthRevokeRequestBuilder(@javax.annotation.Nonnull String token, @javax.annotation.Nullable String clientId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'token' is set
    if (token == null) {
      throw new ApiException(400, "Missing the required parameter 'token' when calling oauthRevoke");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/oauth/revoke";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    List<NameValuePair> formValues = new ArrayList<>();
    if (token != null) {
        formValues.add(new BasicNameValuePair("token", token.toString()));
    }
    if (clientId != null) {
        formValues.add(new BasicNameValuePair("client_id", clientId.toString()));
    }
    HttpEntity entity = new UrlEncodedFormEntity(formValues, java.nio.charset.StandardCharsets.UTF_8);
    ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
    try {
        entity.writeTo(formOutputStream);
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
    byte[] formBytes = formOutputStream.toByteArray();
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formBytes)));
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Token
   * Three grant types.  &#x60;urn:ietf:params:oauth:grant-type:device_code&#x60; polls a device authorization. Until the person approves it answers &#x60;authorization_pending&#x60;; poll faster than &#x60;interval&#x60; and it answers &#x60;slow_down&#x60;, which means widen your interval and keep it widened.  &#x60;authorization_code&#x60; exchanges a code from &#x60;/oauth/authorize&#x60;, with the &#x60;code_verifier&#x60; matching the challenge you sent.  &#x60;refresh_token&#x60; exchanges a refresh token. The presented token is consumed whatever happens next, so store the new one before using it. 
   * @param grantType  (required)
   * @param clientId  (required)
   * @param deviceCode  (optional)
   * @param code  (optional)
   * @param codeVerifier  (optional)
   * @param redirectUri  (optional)
   * @param refreshToken  (optional)
   * @return TokenResponse
   * @throws ApiException if fails to make API call
   */
  public TokenResponse oauthToken(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nullable String deviceCode, @javax.annotation.Nullable String code, @javax.annotation.Nullable String codeVerifier, @javax.annotation.Nullable String redirectUri, @javax.annotation.Nullable String refreshToken) throws ApiException {
    return oauthToken(grantType, clientId, deviceCode, code, codeVerifier, redirectUri, refreshToken, null);
  }

  /**
   * Token
   * Three grant types.  &#x60;urn:ietf:params:oauth:grant-type:device_code&#x60; polls a device authorization. Until the person approves it answers &#x60;authorization_pending&#x60;; poll faster than &#x60;interval&#x60; and it answers &#x60;slow_down&#x60;, which means widen your interval and keep it widened.  &#x60;authorization_code&#x60; exchanges a code from &#x60;/oauth/authorize&#x60;, with the &#x60;code_verifier&#x60; matching the challenge you sent.  &#x60;refresh_token&#x60; exchanges a refresh token. The presented token is consumed whatever happens next, so store the new one before using it. 
   * @param grantType  (required)
   * @param clientId  (required)
   * @param deviceCode  (optional)
   * @param code  (optional)
   * @param codeVerifier  (optional)
   * @param redirectUri  (optional)
   * @param refreshToken  (optional)
   * @param headers Optional headers to include in the request
   * @return TokenResponse
   * @throws ApiException if fails to make API call
   */
  public TokenResponse oauthToken(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nullable String deviceCode, @javax.annotation.Nullable String code, @javax.annotation.Nullable String codeVerifier, @javax.annotation.Nullable String redirectUri, @javax.annotation.Nullable String refreshToken, Map<String, String> headers) throws ApiException {
    ApiResponse<TokenResponse> localVarResponse = oauthTokenWithHttpInfo(grantType, clientId, deviceCode, code, codeVerifier, redirectUri, refreshToken, headers);
    return localVarResponse.getData();
  }

  /**
   * Token
   * Three grant types.  &#x60;urn:ietf:params:oauth:grant-type:device_code&#x60; polls a device authorization. Until the person approves it answers &#x60;authorization_pending&#x60;; poll faster than &#x60;interval&#x60; and it answers &#x60;slow_down&#x60;, which means widen your interval and keep it widened.  &#x60;authorization_code&#x60; exchanges a code from &#x60;/oauth/authorize&#x60;, with the &#x60;code_verifier&#x60; matching the challenge you sent.  &#x60;refresh_token&#x60; exchanges a refresh token. The presented token is consumed whatever happens next, so store the new one before using it. 
   * @param grantType  (required)
   * @param clientId  (required)
   * @param deviceCode  (optional)
   * @param code  (optional)
   * @param codeVerifier  (optional)
   * @param redirectUri  (optional)
   * @param refreshToken  (optional)
   * @return ApiResponse&lt;TokenResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TokenResponse> oauthTokenWithHttpInfo(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nullable String deviceCode, @javax.annotation.Nullable String code, @javax.annotation.Nullable String codeVerifier, @javax.annotation.Nullable String redirectUri, @javax.annotation.Nullable String refreshToken) throws ApiException {
    return oauthTokenWithHttpInfo(grantType, clientId, deviceCode, code, codeVerifier, redirectUri, refreshToken, null);
  }

  /**
   * Token
   * Three grant types.  &#x60;urn:ietf:params:oauth:grant-type:device_code&#x60; polls a device authorization. Until the person approves it answers &#x60;authorization_pending&#x60;; poll faster than &#x60;interval&#x60; and it answers &#x60;slow_down&#x60;, which means widen your interval and keep it widened.  &#x60;authorization_code&#x60; exchanges a code from &#x60;/oauth/authorize&#x60;, with the &#x60;code_verifier&#x60; matching the challenge you sent.  &#x60;refresh_token&#x60; exchanges a refresh token. The presented token is consumed whatever happens next, so store the new one before using it. 
   * @param grantType  (required)
   * @param clientId  (required)
   * @param deviceCode  (optional)
   * @param code  (optional)
   * @param codeVerifier  (optional)
   * @param redirectUri  (optional)
   * @param refreshToken  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TokenResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TokenResponse> oauthTokenWithHttpInfo(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nullable String deviceCode, @javax.annotation.Nullable String code, @javax.annotation.Nullable String codeVerifier, @javax.annotation.Nullable String redirectUri, @javax.annotation.Nullable String refreshToken, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = oauthTokenRequestBuilder(grantType, clientId, deviceCode, code, codeVerifier, redirectUri, refreshToken, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("oauthToken", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<TokenResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        TokenResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TokenResponse>() {});
        

        return new ApiResponse<TokenResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder oauthTokenRequestBuilder(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nullable String deviceCode, @javax.annotation.Nullable String code, @javax.annotation.Nullable String codeVerifier, @javax.annotation.Nullable String redirectUri, @javax.annotation.Nullable String refreshToken, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'grantType' is set
    if (grantType == null) {
      throw new ApiException(400, "Missing the required parameter 'grantType' when calling oauthToken");
    }
    // verify the required parameter 'clientId' is set
    if (clientId == null) {
      throw new ApiException(400, "Missing the required parameter 'clientId' when calling oauthToken");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/oauth/token";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    List<NameValuePair> formValues = new ArrayList<>();
    if (grantType != null) {
        formValues.add(new BasicNameValuePair("grant_type", grantType.toString()));
    }
    if (clientId != null) {
        formValues.add(new BasicNameValuePair("client_id", clientId.toString()));
    }
    if (deviceCode != null) {
        formValues.add(new BasicNameValuePair("device_code", deviceCode.toString()));
    }
    if (code != null) {
        formValues.add(new BasicNameValuePair("code", code.toString()));
    }
    if (codeVerifier != null) {
        formValues.add(new BasicNameValuePair("code_verifier", codeVerifier.toString()));
    }
    if (redirectUri != null) {
        formValues.add(new BasicNameValuePair("redirect_uri", redirectUri.toString()));
    }
    if (refreshToken != null) {
        formValues.add(new BasicNameValuePair("refresh_token", refreshToken.toString()));
    }
    HttpEntity entity = new UrlEncodedFormEntity(formValues, java.nio.charset.StandardCharsets.UTF_8);
    ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
    try {
        entity.writeTo(formOutputStream);
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
    byte[] formBytes = formOutputStream.toByteArray();
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formBytes)));
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
