/*
 * VPNDetection API
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries. 
 *
 * The version of the OpenAPI document: 2026.09.03
 * Contact: support@vpndetection.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vpndetection.api;

import io.vpndetection.internal.ApiClient;
import io.vpndetection.internal.ApiException;
import io.vpndetection.internal.ApiResponse;
import io.vpndetection.internal.Configuration;
import io.vpndetection.internal.Pair;

import io.vpndetection.model.DatabaseChecksum200Response;
import io.vpndetection.model.DatasetMetadata;
import io.vpndetection.model.Error;
import io.vpndetection.model.ListDatabases200Response;
import io.vpndetection.model.ListDownloads200Response;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DatabaseApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public DatabaseApi() {
    this(Configuration.getDefaultApiClient());
  }

  public DatabaseApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Checksums for one published file, to verify a download
   * 
   * @param id  (required)
   * @param format  (required)
   * @return DatabaseChecksum200Response
   * @throws ApiException if fails to make API call
   */
  public DatabaseChecksum200Response databaseChecksum(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format) throws ApiException {
    return databaseChecksum(id, format, null);
  }

  /**
   * Checksums for one published file, to verify a download
   * 
   * @param id  (required)
   * @param format  (required)
   * @param headers Optional headers to include in the request
   * @return DatabaseChecksum200Response
   * @throws ApiException if fails to make API call
   */
  public DatabaseChecksum200Response databaseChecksum(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    ApiResponse<DatabaseChecksum200Response> localVarResponse = databaseChecksumWithHttpInfo(id, format, headers);
    return localVarResponse.getData();
  }

  /**
   * Checksums for one published file, to verify a download
   * 
   * @param id  (required)
   * @param format  (required)
   * @return ApiResponse&lt;DatabaseChecksum200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DatabaseChecksum200Response> databaseChecksumWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format) throws ApiException {
    return databaseChecksumWithHttpInfo(id, format, null);
  }

  /**
   * Checksums for one published file, to verify a download
   * 
   * @param id  (required)
   * @param format  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DatabaseChecksum200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DatabaseChecksum200Response> databaseChecksumWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = databaseChecksumRequestBuilder(id, format, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("databaseChecksum", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DatabaseChecksum200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DatabaseChecksum200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DatabaseChecksum200Response>() {});
        

        return new ApiResponse<DatabaseChecksum200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder databaseChecksumRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling databaseChecksum");
    }
    // verify the required parameter 'format' is set
    if (format == null) {
      throw new ApiException(400, "Missing the required parameter 'format' when calling databaseChecksum");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/database/checksum";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("id", id));
    localVarQueryParameterBaseName = "format";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("format", format));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * What is inside one dataset - schema, samples, row count, sizes
   * Poll this to decide whether today&#39;s build is worth fetching: it carries &#x60;updated&#x60; and &#x60;entries&#x60; without downloading anything.  No &#x60;format&#x60; parameter - one document describes every format the dataset is built in. 
   * @param id  (required)
   * @return DatasetMetadata
   * @throws ApiException if fails to make API call
   */
  public DatasetMetadata databaseMetadata(@javax.annotation.Nonnull String id) throws ApiException {
    return databaseMetadata(id, null);
  }

  /**
   * What is inside one dataset - schema, samples, row count, sizes
   * Poll this to decide whether today&#39;s build is worth fetching: it carries &#x60;updated&#x60; and &#x60;entries&#x60; without downloading anything.  No &#x60;format&#x60; parameter - one document describes every format the dataset is built in. 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return DatasetMetadata
   * @throws ApiException if fails to make API call
   */
  public DatasetMetadata databaseMetadata(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<DatasetMetadata> localVarResponse = databaseMetadataWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * What is inside one dataset - schema, samples, row count, sizes
   * Poll this to decide whether today&#39;s build is worth fetching: it carries &#x60;updated&#x60; and &#x60;entries&#x60; without downloading anything.  No &#x60;format&#x60; parameter - one document describes every format the dataset is built in. 
   * @param id  (required)
   * @return ApiResponse&lt;DatasetMetadata&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DatasetMetadata> databaseMetadataWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return databaseMetadataWithHttpInfo(id, null);
  }

  /**
   * What is inside one dataset - schema, samples, row count, sizes
   * Poll this to decide whether today&#39;s build is worth fetching: it carries &#x60;updated&#x60; and &#x60;entries&#x60; without downloading anything.  No &#x60;format&#x60; parameter - one document describes every format the dataset is built in. 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DatasetMetadata&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DatasetMetadata> databaseMetadataWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = databaseMetadataRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("databaseMetadata", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DatasetMetadata>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DatasetMetadata responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DatasetMetadata>() {});
        

        return new ApiResponse<DatasetMetadata>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder databaseMetadataRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling databaseMetadata");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/database/metadata";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("id", id));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Redirect to a time-limited download URL for one dataset
   * 
   * @param id Dataset id, e.g. vpn_ip_extended_v1 (required)
   * @param format Not every dataset is built in every format. The &#x60;_provider&#x60; catalogues are keyed by provider id rather than by IP range, so no MMDB exists for them.  (required)
   * @throws ApiException if fails to make API call
   */
  public void downloadDatabase(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format) throws ApiException {
    downloadDatabase(id, format, null);
  }

  /**
   * Redirect to a time-limited download URL for one dataset
   * 
   * @param id Dataset id, e.g. vpn_ip_extended_v1 (required)
   * @param format Not every dataset is built in every format. The &#x60;_provider&#x60; catalogues are keyed by provider id rather than by IP range, so no MMDB exists for them.  (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void downloadDatabase(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    downloadDatabaseWithHttpInfo(id, format, headers);
  }

  /**
   * Redirect to a time-limited download URL for one dataset
   * 
   * @param id Dataset id, e.g. vpn_ip_extended_v1 (required)
   * @param format Not every dataset is built in every format. The &#x60;_provider&#x60; catalogues are keyed by provider id rather than by IP range, so no MMDB exists for them.  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> downloadDatabaseWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format) throws ApiException {
    return downloadDatabaseWithHttpInfo(id, format, null);
  }

  /**
   * Redirect to a time-limited download URL for one dataset
   * 
   * @param id Dataset id, e.g. vpn_ip_extended_v1 (required)
   * @param format Not every dataset is built in every format. The &#x60;_provider&#x60; catalogues are keyed by provider id rather than by IP range, so no MMDB exists for them.  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> downloadDatabaseWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = downloadDatabaseRequestBuilder(id, format, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("downloadDatabase", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder downloadDatabaseRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling downloadDatabase");
    }
    // verify the required parameter 'format' is set
    if (format == null) {
      throw new ApiException(400, "Missing the required parameter 'format' when calling downloadDatabase");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/database/download";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("id", id));
    localVarQueryParameterBaseName = "format";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("format", format));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * The datasets your organization is licensed to download
   * 
   * @return ListDatabases200Response
   * @throws ApiException if fails to make API call
   */
  public ListDatabases200Response listDatabases() throws ApiException {
    return listDatabases(null);
  }

  /**
   * The datasets your organization is licensed to download
   * 
   * @param headers Optional headers to include in the request
   * @return ListDatabases200Response
   * @throws ApiException if fails to make API call
   */
  public ListDatabases200Response listDatabases(Map<String, String> headers) throws ApiException {
    ApiResponse<ListDatabases200Response> localVarResponse = listDatabasesWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * The datasets your organization is licensed to download
   * 
   * @return ApiResponse&lt;ListDatabases200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListDatabases200Response> listDatabasesWithHttpInfo() throws ApiException {
    return listDatabasesWithHttpInfo(null);
  }

  /**
   * The datasets your organization is licensed to download
   * 
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ListDatabases200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListDatabases200Response> listDatabasesWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listDatabasesRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listDatabases", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ListDatabases200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ListDatabases200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ListDatabases200Response>() {});
        

        return new ApiResponse<ListDatabases200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listDatabasesRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/database/list";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Your organization&#39;s recent download attempts, newest first
   * 
   * @param limit  (optional, default to 50)
   * @return ListDownloads200Response
   * @throws ApiException if fails to make API call
   */
  public ListDownloads200Response listDownloads(@javax.annotation.Nullable Integer limit) throws ApiException {
    return listDownloads(limit, null);
  }

  /**
   * Your organization&#39;s recent download attempts, newest first
   * 
   * @param limit  (optional, default to 50)
   * @param headers Optional headers to include in the request
   * @return ListDownloads200Response
   * @throws ApiException if fails to make API call
   */
  public ListDownloads200Response listDownloads(@javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    ApiResponse<ListDownloads200Response> localVarResponse = listDownloadsWithHttpInfo(limit, headers);
    return localVarResponse.getData();
  }

  /**
   * Your organization&#39;s recent download attempts, newest first
   * 
   * @param limit  (optional, default to 50)
   * @return ApiResponse&lt;ListDownloads200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListDownloads200Response> listDownloadsWithHttpInfo(@javax.annotation.Nullable Integer limit) throws ApiException {
    return listDownloadsWithHttpInfo(limit, null);
  }

  /**
   * Your organization&#39;s recent download attempts, newest first
   * 
   * @param limit  (optional, default to 50)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ListDownloads200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListDownloads200Response> listDownloadsWithHttpInfo(@javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listDownloadsRequestBuilder(limit, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listDownloads", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ListDownloads200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ListDownloads200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ListDownloads200Response>() {});
        

        return new ApiResponse<ListDownloads200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listDownloadsRequestBuilder(@javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/database/downloads";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
